// Code generated by ent, DO NOT EDIT.

package providercurrencies

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the providercurrencies type in the database.
	Label = "provider_currencies"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAvailableBalance holds the string denoting the available_balance field in the database.
	FieldAvailableBalance = "available_balance"
	// FieldTotalBalance holds the string denoting the total_balance field in the database.
	FieldTotalBalance = "total_balance"
	// FieldReservedBalance holds the string denoting the reserved_balance field in the database.
	FieldReservedBalance = "reserved_balance"
	// FieldIsAvailable holds the string denoting the is_available field in the database.
	FieldIsAvailable = "is_available"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// EdgeCurrency holds the string denoting the currency edge name in mutations.
	EdgeCurrency = "currency"
	// Table holds the table name of the providercurrencies in the database.
	Table = "provider_currencies"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "provider_currencies"
	// ProviderInverseTable is the table name for the ProviderProfile entity.
	// It exists in this package in order to avoid circular dependency with the "providerprofile" package.
	ProviderInverseTable = "provider_profiles"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "provider_profile_provider_currencies"
	// CurrencyTable is the table that holds the currency relation/edge.
	CurrencyTable = "provider_currencies"
	// CurrencyInverseTable is the table name for the FiatCurrency entity.
	// It exists in this package in order to avoid circular dependency with the "fiatcurrency" package.
	CurrencyInverseTable = "fiat_currencies"
	// CurrencyColumn is the table column denoting the currency relation/edge.
	CurrencyColumn = "fiat_currency_provider_currencies"
)

// Columns holds all SQL columns for providercurrencies fields.
var Columns = []string{
	FieldID,
	FieldAvailableBalance,
	FieldTotalBalance,
	FieldReservedBalance,
	FieldIsAvailable,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "provider_currencies"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"fiat_currency_provider_currencies",
	"provider_profile_provider_currencies",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsAvailable holds the default value on creation for the "is_available" field.
	DefaultIsAvailable bool
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ProviderCurrencies queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAvailableBalance orders the results by the available_balance field.
func ByAvailableBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableBalance, opts...).ToFunc()
}

// ByTotalBalance orders the results by the total_balance field.
func ByTotalBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalBalance, opts...).ToFunc()
}

// ByReservedBalance orders the results by the reserved_balance field.
func ByReservedBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedBalance, opts...).ToFunc()
}

// ByIsAvailable orders the results by the is_available field.
func ByIsAvailable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAvailable, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProviderField orders the results by provider field.
func ByProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderStep(), sql.OrderByField(field, opts...))
	}
}

// ByCurrencyField orders the results by currency field.
func ByCurrencyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCurrencyStep(), sql.OrderByField(field, opts...))
	}
}
func newProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
	)
}
func newCurrencyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CurrencyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CurrencyTable, CurrencyColumn),
	)
}
