// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/paycrest/aggregator/ent/fiatcurrency"
	"github.com/paycrest/aggregator/ent/institution"
	"github.com/paycrest/aggregator/ent/predicate"
	"github.com/paycrest/aggregator/ent/providerbalances"
	"github.com/paycrest/aggregator/ent/providerordertoken"
	"github.com/paycrest/aggregator/ent/provisionbucket"
	"github.com/shopspring/decimal"
)

// FiatCurrencyUpdate is the builder for updating FiatCurrency entities.
type FiatCurrencyUpdate struct {
	config
	hooks    []Hook
	mutation *FiatCurrencyMutation
}

// Where appends a list predicates to the FiatCurrencyUpdate builder.
func (_u *FiatCurrencyUpdate) Where(ps ...predicate.FiatCurrency) *FiatCurrencyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FiatCurrencyUpdate) SetUpdatedAt(v time.Time) *FiatCurrencyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *FiatCurrencyUpdate) SetCode(v string) *FiatCurrencyUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *FiatCurrencyUpdate) SetNillableCode(v *string) *FiatCurrencyUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetShortName sets the "short_name" field.
func (_u *FiatCurrencyUpdate) SetShortName(v string) *FiatCurrencyUpdate {
	_u.mutation.SetShortName(v)
	return _u
}

// SetNillableShortName sets the "short_name" field if the given value is not nil.
func (_u *FiatCurrencyUpdate) SetNillableShortName(v *string) *FiatCurrencyUpdate {
	if v != nil {
		_u.SetShortName(*v)
	}
	return _u
}

// SetDecimals sets the "decimals" field.
func (_u *FiatCurrencyUpdate) SetDecimals(v int) *FiatCurrencyUpdate {
	_u.mutation.ResetDecimals()
	_u.mutation.SetDecimals(v)
	return _u
}

// SetNillableDecimals sets the "decimals" field if the given value is not nil.
func (_u *FiatCurrencyUpdate) SetNillableDecimals(v *int) *FiatCurrencyUpdate {
	if v != nil {
		_u.SetDecimals(*v)
	}
	return _u
}

// AddDecimals adds value to the "decimals" field.
func (_u *FiatCurrencyUpdate) AddDecimals(v int) *FiatCurrencyUpdate {
	_u.mutation.AddDecimals(v)
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *FiatCurrencyUpdate) SetSymbol(v string) *FiatCurrencyUpdate {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *FiatCurrencyUpdate) SetNillableSymbol(v *string) *FiatCurrencyUpdate {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *FiatCurrencyUpdate) SetName(v string) *FiatCurrencyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FiatCurrencyUpdate) SetNillableName(v *string) *FiatCurrencyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMarketBuyRate sets the "market_buy_rate" field.
func (_u *FiatCurrencyUpdate) SetMarketBuyRate(v decimal.Decimal) *FiatCurrencyUpdate {
	_u.mutation.ResetMarketBuyRate()
	_u.mutation.SetMarketBuyRate(v)
	return _u
}

// SetNillableMarketBuyRate sets the "market_buy_rate" field if the given value is not nil.
func (_u *FiatCurrencyUpdate) SetNillableMarketBuyRate(v *decimal.Decimal) *FiatCurrencyUpdate {
	if v != nil {
		_u.SetMarketBuyRate(*v)
	}
	return _u
}

// AddMarketBuyRate adds value to the "market_buy_rate" field.
func (_u *FiatCurrencyUpdate) AddMarketBuyRate(v decimal.Decimal) *FiatCurrencyUpdate {
	_u.mutation.AddMarketBuyRate(v)
	return _u
}

// ClearMarketBuyRate clears the value of the "market_buy_rate" field.
func (_u *FiatCurrencyUpdate) ClearMarketBuyRate() *FiatCurrencyUpdate {
	_u.mutation.ClearMarketBuyRate()
	return _u
}

// SetMarketSellRate sets the "market_sell_rate" field.
func (_u *FiatCurrencyUpdate) SetMarketSellRate(v decimal.Decimal) *FiatCurrencyUpdate {
	_u.mutation.ResetMarketSellRate()
	_u.mutation.SetMarketSellRate(v)
	return _u
}

// SetNillableMarketSellRate sets the "market_sell_rate" field if the given value is not nil.
func (_u *FiatCurrencyUpdate) SetNillableMarketSellRate(v *decimal.Decimal) *FiatCurrencyUpdate {
	if v != nil {
		_u.SetMarketSellRate(*v)
	}
	return _u
}

// AddMarketSellRate adds value to the "market_sell_rate" field.
func (_u *FiatCurrencyUpdate) AddMarketSellRate(v decimal.Decimal) *FiatCurrencyUpdate {
	_u.mutation.AddMarketSellRate(v)
	return _u
}

// ClearMarketSellRate clears the value of the "market_sell_rate" field.
func (_u *FiatCurrencyUpdate) ClearMarketSellRate() *FiatCurrencyUpdate {
	_u.mutation.ClearMarketSellRate()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *FiatCurrencyUpdate) SetIsEnabled(v bool) *FiatCurrencyUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *FiatCurrencyUpdate) SetNillableIsEnabled(v *bool) *FiatCurrencyUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// AddProviderBalanceIDs adds the "provider_balances" edge to the ProviderBalances entity by IDs.
func (_u *FiatCurrencyUpdate) AddProviderBalanceIDs(ids ...uuid.UUID) *FiatCurrencyUpdate {
	_u.mutation.AddProviderBalanceIDs(ids...)
	return _u
}

// AddProviderBalances adds the "provider_balances" edges to the ProviderBalances entity.
func (_u *FiatCurrencyUpdate) AddProviderBalances(v ...*ProviderBalances) *FiatCurrencyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProviderBalanceIDs(ids...)
}

// AddProvisionBucketIDs adds the "provision_buckets" edge to the ProvisionBucket entity by IDs.
func (_u *FiatCurrencyUpdate) AddProvisionBucketIDs(ids ...int) *FiatCurrencyUpdate {
	_u.mutation.AddProvisionBucketIDs(ids...)
	return _u
}

// AddProvisionBuckets adds the "provision_buckets" edges to the ProvisionBucket entity.
func (_u *FiatCurrencyUpdate) AddProvisionBuckets(v ...*ProvisionBucket) *FiatCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProvisionBucketIDs(ids...)
}

// AddInstitutionIDs adds the "institutions" edge to the Institution entity by IDs.
func (_u *FiatCurrencyUpdate) AddInstitutionIDs(ids ...int) *FiatCurrencyUpdate {
	_u.mutation.AddInstitutionIDs(ids...)
	return _u
}

// AddInstitutions adds the "institutions" edges to the Institution entity.
func (_u *FiatCurrencyUpdate) AddInstitutions(v ...*Institution) *FiatCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstitutionIDs(ids...)
}

// AddProviderOrderTokenIDs adds the "provider_order_tokens" edge to the ProviderOrderToken entity by IDs.
func (_u *FiatCurrencyUpdate) AddProviderOrderTokenIDs(ids ...int) *FiatCurrencyUpdate {
	_u.mutation.AddProviderOrderTokenIDs(ids...)
	return _u
}

// AddProviderOrderTokens adds the "provider_order_tokens" edges to the ProviderOrderToken entity.
func (_u *FiatCurrencyUpdate) AddProviderOrderTokens(v ...*ProviderOrderToken) *FiatCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProviderOrderTokenIDs(ids...)
}

// Mutation returns the FiatCurrencyMutation object of the builder.
func (_u *FiatCurrencyUpdate) Mutation() *FiatCurrencyMutation {
	return _u.mutation
}

// ClearProviderBalances clears all "provider_balances" edges to the ProviderBalances entity.
func (_u *FiatCurrencyUpdate) ClearProviderBalances() *FiatCurrencyUpdate {
	_u.mutation.ClearProviderBalances()
	return _u
}

// RemoveProviderBalanceIDs removes the "provider_balances" edge to ProviderBalances entities by IDs.
func (_u *FiatCurrencyUpdate) RemoveProviderBalanceIDs(ids ...uuid.UUID) *FiatCurrencyUpdate {
	_u.mutation.RemoveProviderBalanceIDs(ids...)
	return _u
}

// RemoveProviderBalances removes "provider_balances" edges to ProviderBalances entities.
func (_u *FiatCurrencyUpdate) RemoveProviderBalances(v ...*ProviderBalances) *FiatCurrencyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProviderBalanceIDs(ids...)
}

// ClearProvisionBuckets clears all "provision_buckets" edges to the ProvisionBucket entity.
func (_u *FiatCurrencyUpdate) ClearProvisionBuckets() *FiatCurrencyUpdate {
	_u.mutation.ClearProvisionBuckets()
	return _u
}

// RemoveProvisionBucketIDs removes the "provision_buckets" edge to ProvisionBucket entities by IDs.
func (_u *FiatCurrencyUpdate) RemoveProvisionBucketIDs(ids ...int) *FiatCurrencyUpdate {
	_u.mutation.RemoveProvisionBucketIDs(ids...)
	return _u
}

// RemoveProvisionBuckets removes "provision_buckets" edges to ProvisionBucket entities.
func (_u *FiatCurrencyUpdate) RemoveProvisionBuckets(v ...*ProvisionBucket) *FiatCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProvisionBucketIDs(ids...)
}

// ClearInstitutions clears all "institutions" edges to the Institution entity.
func (_u *FiatCurrencyUpdate) ClearInstitutions() *FiatCurrencyUpdate {
	_u.mutation.ClearInstitutions()
	return _u
}

// RemoveInstitutionIDs removes the "institutions" edge to Institution entities by IDs.
func (_u *FiatCurrencyUpdate) RemoveInstitutionIDs(ids ...int) *FiatCurrencyUpdate {
	_u.mutation.RemoveInstitutionIDs(ids...)
	return _u
}

// RemoveInstitutions removes "institutions" edges to Institution entities.
func (_u *FiatCurrencyUpdate) RemoveInstitutions(v ...*Institution) *FiatCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstitutionIDs(ids...)
}

// ClearProviderOrderTokens clears all "provider_order_tokens" edges to the ProviderOrderToken entity.
func (_u *FiatCurrencyUpdate) ClearProviderOrderTokens() *FiatCurrencyUpdate {
	_u.mutation.ClearProviderOrderTokens()
	return _u
}

// RemoveProviderOrderTokenIDs removes the "provider_order_tokens" edge to ProviderOrderToken entities by IDs.
func (_u *FiatCurrencyUpdate) RemoveProviderOrderTokenIDs(ids ...int) *FiatCurrencyUpdate {
	_u.mutation.RemoveProviderOrderTokenIDs(ids...)
	return _u
}

// RemoveProviderOrderTokens removes "provider_order_tokens" edges to ProviderOrderToken entities.
func (_u *FiatCurrencyUpdate) RemoveProviderOrderTokens(v ...*ProviderOrderToken) *FiatCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProviderOrderTokenIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FiatCurrencyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FiatCurrencyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FiatCurrencyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FiatCurrencyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FiatCurrencyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := fiatcurrency.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *FiatCurrencyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(fiatcurrency.Table, fiatcurrency.Columns, sqlgraph.NewFieldSpec(fiatcurrency.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fiatcurrency.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(fiatcurrency.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShortName(); ok {
		_spec.SetField(fiatcurrency.FieldShortName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Decimals(); ok {
		_spec.SetField(fiatcurrency.FieldDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDecimals(); ok {
		_spec.AddField(fiatcurrency.FieldDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(fiatcurrency.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(fiatcurrency.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MarketBuyRate(); ok {
		_spec.SetField(fiatcurrency.FieldMarketBuyRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketBuyRate(); ok {
		_spec.AddField(fiatcurrency.FieldMarketBuyRate, field.TypeFloat64, value)
	}
	if _u.mutation.MarketBuyRateCleared() {
		_spec.ClearField(fiatcurrency.FieldMarketBuyRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MarketSellRate(); ok {
		_spec.SetField(fiatcurrency.FieldMarketSellRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketSellRate(); ok {
		_spec.AddField(fiatcurrency.FieldMarketSellRate, field.TypeFloat64, value)
	}
	if _u.mutation.MarketSellRateCleared() {
		_spec.ClearField(fiatcurrency.FieldMarketSellRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(fiatcurrency.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.ProviderBalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProviderBalancesTable,
			Columns: []string{fiatcurrency.ProviderBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerbalances.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProviderBalancesIDs(); len(nodes) > 0 && !_u.mutation.ProviderBalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProviderBalancesTable,
			Columns: []string{fiatcurrency.ProviderBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerbalances.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderBalancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProviderBalancesTable,
			Columns: []string{fiatcurrency.ProviderBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerbalances.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProvisionBucketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProvisionBucketsTable,
			Columns: []string{fiatcurrency.ProvisionBucketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provisionbucket.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProvisionBucketsIDs(); len(nodes) > 0 && !_u.mutation.ProvisionBucketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProvisionBucketsTable,
			Columns: []string{fiatcurrency.ProvisionBucketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provisionbucket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProvisionBucketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProvisionBucketsTable,
			Columns: []string{fiatcurrency.ProvisionBucketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provisionbucket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InstitutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.InstitutionsTable,
			Columns: []string{fiatcurrency.InstitutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(institution.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstitutionsIDs(); len(nodes) > 0 && !_u.mutation.InstitutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.InstitutionsTable,
			Columns: []string{fiatcurrency.InstitutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(institution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstitutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.InstitutionsTable,
			Columns: []string{fiatcurrency.InstitutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(institution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProviderOrderTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProviderOrderTokensTable,
			Columns: []string{fiatcurrency.ProviderOrderTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerordertoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProviderOrderTokensIDs(); len(nodes) > 0 && !_u.mutation.ProviderOrderTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProviderOrderTokensTable,
			Columns: []string{fiatcurrency.ProviderOrderTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerordertoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderOrderTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProviderOrderTokensTable,
			Columns: []string{fiatcurrency.ProviderOrderTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerordertoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fiatcurrency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FiatCurrencyUpdateOne is the builder for updating a single FiatCurrency entity.
type FiatCurrencyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FiatCurrencyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FiatCurrencyUpdateOne) SetUpdatedAt(v time.Time) *FiatCurrencyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *FiatCurrencyUpdateOne) SetCode(v string) *FiatCurrencyUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *FiatCurrencyUpdateOne) SetNillableCode(v *string) *FiatCurrencyUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetShortName sets the "short_name" field.
func (_u *FiatCurrencyUpdateOne) SetShortName(v string) *FiatCurrencyUpdateOne {
	_u.mutation.SetShortName(v)
	return _u
}

// SetNillableShortName sets the "short_name" field if the given value is not nil.
func (_u *FiatCurrencyUpdateOne) SetNillableShortName(v *string) *FiatCurrencyUpdateOne {
	if v != nil {
		_u.SetShortName(*v)
	}
	return _u
}

// SetDecimals sets the "decimals" field.
func (_u *FiatCurrencyUpdateOne) SetDecimals(v int) *FiatCurrencyUpdateOne {
	_u.mutation.ResetDecimals()
	_u.mutation.SetDecimals(v)
	return _u
}

// SetNillableDecimals sets the "decimals" field if the given value is not nil.
func (_u *FiatCurrencyUpdateOne) SetNillableDecimals(v *int) *FiatCurrencyUpdateOne {
	if v != nil {
		_u.SetDecimals(*v)
	}
	return _u
}

// AddDecimals adds value to the "decimals" field.
func (_u *FiatCurrencyUpdateOne) AddDecimals(v int) *FiatCurrencyUpdateOne {
	_u.mutation.AddDecimals(v)
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *FiatCurrencyUpdateOne) SetSymbol(v string) *FiatCurrencyUpdateOne {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *FiatCurrencyUpdateOne) SetNillableSymbol(v *string) *FiatCurrencyUpdateOne {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *FiatCurrencyUpdateOne) SetName(v string) *FiatCurrencyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FiatCurrencyUpdateOne) SetNillableName(v *string) *FiatCurrencyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMarketBuyRate sets the "market_buy_rate" field.
func (_u *FiatCurrencyUpdateOne) SetMarketBuyRate(v decimal.Decimal) *FiatCurrencyUpdateOne {
	_u.mutation.ResetMarketBuyRate()
	_u.mutation.SetMarketBuyRate(v)
	return _u
}

// SetNillableMarketBuyRate sets the "market_buy_rate" field if the given value is not nil.
func (_u *FiatCurrencyUpdateOne) SetNillableMarketBuyRate(v *decimal.Decimal) *FiatCurrencyUpdateOne {
	if v != nil {
		_u.SetMarketBuyRate(*v)
	}
	return _u
}

// AddMarketBuyRate adds value to the "market_buy_rate" field.
func (_u *FiatCurrencyUpdateOne) AddMarketBuyRate(v decimal.Decimal) *FiatCurrencyUpdateOne {
	_u.mutation.AddMarketBuyRate(v)
	return _u
}

// ClearMarketBuyRate clears the value of the "market_buy_rate" field.
func (_u *FiatCurrencyUpdateOne) ClearMarketBuyRate() *FiatCurrencyUpdateOne {
	_u.mutation.ClearMarketBuyRate()
	return _u
}

// SetMarketSellRate sets the "market_sell_rate" field.
func (_u *FiatCurrencyUpdateOne) SetMarketSellRate(v decimal.Decimal) *FiatCurrencyUpdateOne {
	_u.mutation.ResetMarketSellRate()
	_u.mutation.SetMarketSellRate(v)
	return _u
}

// SetNillableMarketSellRate sets the "market_sell_rate" field if the given value is not nil.
func (_u *FiatCurrencyUpdateOne) SetNillableMarketSellRate(v *decimal.Decimal) *FiatCurrencyUpdateOne {
	if v != nil {
		_u.SetMarketSellRate(*v)
	}
	return _u
}

// AddMarketSellRate adds value to the "market_sell_rate" field.
func (_u *FiatCurrencyUpdateOne) AddMarketSellRate(v decimal.Decimal) *FiatCurrencyUpdateOne {
	_u.mutation.AddMarketSellRate(v)
	return _u
}

// ClearMarketSellRate clears the value of the "market_sell_rate" field.
func (_u *FiatCurrencyUpdateOne) ClearMarketSellRate() *FiatCurrencyUpdateOne {
	_u.mutation.ClearMarketSellRate()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *FiatCurrencyUpdateOne) SetIsEnabled(v bool) *FiatCurrencyUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *FiatCurrencyUpdateOne) SetNillableIsEnabled(v *bool) *FiatCurrencyUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// AddProviderBalanceIDs adds the "provider_balances" edge to the ProviderBalances entity by IDs.
func (_u *FiatCurrencyUpdateOne) AddProviderBalanceIDs(ids ...uuid.UUID) *FiatCurrencyUpdateOne {
	_u.mutation.AddProviderBalanceIDs(ids...)
	return _u
}

// AddProviderBalances adds the "provider_balances" edges to the ProviderBalances entity.
func (_u *FiatCurrencyUpdateOne) AddProviderBalances(v ...*ProviderBalances) *FiatCurrencyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProviderBalanceIDs(ids...)
}

// AddProvisionBucketIDs adds the "provision_buckets" edge to the ProvisionBucket entity by IDs.
func (_u *FiatCurrencyUpdateOne) AddProvisionBucketIDs(ids ...int) *FiatCurrencyUpdateOne {
	_u.mutation.AddProvisionBucketIDs(ids...)
	return _u
}

// AddProvisionBuckets adds the "provision_buckets" edges to the ProvisionBucket entity.
func (_u *FiatCurrencyUpdateOne) AddProvisionBuckets(v ...*ProvisionBucket) *FiatCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProvisionBucketIDs(ids...)
}

// AddInstitutionIDs adds the "institutions" edge to the Institution entity by IDs.
func (_u *FiatCurrencyUpdateOne) AddInstitutionIDs(ids ...int) *FiatCurrencyUpdateOne {
	_u.mutation.AddInstitutionIDs(ids...)
	return _u
}

// AddInstitutions adds the "institutions" edges to the Institution entity.
func (_u *FiatCurrencyUpdateOne) AddInstitutions(v ...*Institution) *FiatCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstitutionIDs(ids...)
}

// AddProviderOrderTokenIDs adds the "provider_order_tokens" edge to the ProviderOrderToken entity by IDs.
func (_u *FiatCurrencyUpdateOne) AddProviderOrderTokenIDs(ids ...int) *FiatCurrencyUpdateOne {
	_u.mutation.AddProviderOrderTokenIDs(ids...)
	return _u
}

// AddProviderOrderTokens adds the "provider_order_tokens" edges to the ProviderOrderToken entity.
func (_u *FiatCurrencyUpdateOne) AddProviderOrderTokens(v ...*ProviderOrderToken) *FiatCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProviderOrderTokenIDs(ids...)
}

// Mutation returns the FiatCurrencyMutation object of the builder.
func (_u *FiatCurrencyUpdateOne) Mutation() *FiatCurrencyMutation {
	return _u.mutation
}

// ClearProviderBalances clears all "provider_balances" edges to the ProviderBalances entity.
func (_u *FiatCurrencyUpdateOne) ClearProviderBalances() *FiatCurrencyUpdateOne {
	_u.mutation.ClearProviderBalances()
	return _u
}

// RemoveProviderBalanceIDs removes the "provider_balances" edge to ProviderBalances entities by IDs.
func (_u *FiatCurrencyUpdateOne) RemoveProviderBalanceIDs(ids ...uuid.UUID) *FiatCurrencyUpdateOne {
	_u.mutation.RemoveProviderBalanceIDs(ids...)
	return _u
}

// RemoveProviderBalances removes "provider_balances" edges to ProviderBalances entities.
func (_u *FiatCurrencyUpdateOne) RemoveProviderBalances(v ...*ProviderBalances) *FiatCurrencyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProviderBalanceIDs(ids...)
}

// ClearProvisionBuckets clears all "provision_buckets" edges to the ProvisionBucket entity.
func (_u *FiatCurrencyUpdateOne) ClearProvisionBuckets() *FiatCurrencyUpdateOne {
	_u.mutation.ClearProvisionBuckets()
	return _u
}

// RemoveProvisionBucketIDs removes the "provision_buckets" edge to ProvisionBucket entities by IDs.
func (_u *FiatCurrencyUpdateOne) RemoveProvisionBucketIDs(ids ...int) *FiatCurrencyUpdateOne {
	_u.mutation.RemoveProvisionBucketIDs(ids...)
	return _u
}

// RemoveProvisionBuckets removes "provision_buckets" edges to ProvisionBucket entities.
func (_u *FiatCurrencyUpdateOne) RemoveProvisionBuckets(v ...*ProvisionBucket) *FiatCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProvisionBucketIDs(ids...)
}

// ClearInstitutions clears all "institutions" edges to the Institution entity.
func (_u *FiatCurrencyUpdateOne) ClearInstitutions() *FiatCurrencyUpdateOne {
	_u.mutation.ClearInstitutions()
	return _u
}

// RemoveInstitutionIDs removes the "institutions" edge to Institution entities by IDs.
func (_u *FiatCurrencyUpdateOne) RemoveInstitutionIDs(ids ...int) *FiatCurrencyUpdateOne {
	_u.mutation.RemoveInstitutionIDs(ids...)
	return _u
}

// RemoveInstitutions removes "institutions" edges to Institution entities.
func (_u *FiatCurrencyUpdateOne) RemoveInstitutions(v ...*Institution) *FiatCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstitutionIDs(ids...)
}

// ClearProviderOrderTokens clears all "provider_order_tokens" edges to the ProviderOrderToken entity.
func (_u *FiatCurrencyUpdateOne) ClearProviderOrderTokens() *FiatCurrencyUpdateOne {
	_u.mutation.ClearProviderOrderTokens()
	return _u
}

// RemoveProviderOrderTokenIDs removes the "provider_order_tokens" edge to ProviderOrderToken entities by IDs.
func (_u *FiatCurrencyUpdateOne) RemoveProviderOrderTokenIDs(ids ...int) *FiatCurrencyUpdateOne {
	_u.mutation.RemoveProviderOrderTokenIDs(ids...)
	return _u
}

// RemoveProviderOrderTokens removes "provider_order_tokens" edges to ProviderOrderToken entities.
func (_u *FiatCurrencyUpdateOne) RemoveProviderOrderTokens(v ...*ProviderOrderToken) *FiatCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProviderOrderTokenIDs(ids...)
}

// Where appends a list predicates to the FiatCurrencyUpdate builder.
func (_u *FiatCurrencyUpdateOne) Where(ps ...predicate.FiatCurrency) *FiatCurrencyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FiatCurrencyUpdateOne) Select(field string, fields ...string) *FiatCurrencyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FiatCurrency entity.
func (_u *FiatCurrencyUpdateOne) Save(ctx context.Context) (*FiatCurrency, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FiatCurrencyUpdateOne) SaveX(ctx context.Context) *FiatCurrency {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FiatCurrencyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FiatCurrencyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FiatCurrencyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := fiatcurrency.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *FiatCurrencyUpdateOne) sqlSave(ctx context.Context) (_node *FiatCurrency, err error) {
	_spec := sqlgraph.NewUpdateSpec(fiatcurrency.Table, fiatcurrency.Columns, sqlgraph.NewFieldSpec(fiatcurrency.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FiatCurrency.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fiatcurrency.FieldID)
		for _, f := range fields {
			if !fiatcurrency.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fiatcurrency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fiatcurrency.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(fiatcurrency.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShortName(); ok {
		_spec.SetField(fiatcurrency.FieldShortName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Decimals(); ok {
		_spec.SetField(fiatcurrency.FieldDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDecimals(); ok {
		_spec.AddField(fiatcurrency.FieldDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(fiatcurrency.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(fiatcurrency.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MarketBuyRate(); ok {
		_spec.SetField(fiatcurrency.FieldMarketBuyRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketBuyRate(); ok {
		_spec.AddField(fiatcurrency.FieldMarketBuyRate, field.TypeFloat64, value)
	}
	if _u.mutation.MarketBuyRateCleared() {
		_spec.ClearField(fiatcurrency.FieldMarketBuyRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MarketSellRate(); ok {
		_spec.SetField(fiatcurrency.FieldMarketSellRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketSellRate(); ok {
		_spec.AddField(fiatcurrency.FieldMarketSellRate, field.TypeFloat64, value)
	}
	if _u.mutation.MarketSellRateCleared() {
		_spec.ClearField(fiatcurrency.FieldMarketSellRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(fiatcurrency.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.ProviderBalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProviderBalancesTable,
			Columns: []string{fiatcurrency.ProviderBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerbalances.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProviderBalancesIDs(); len(nodes) > 0 && !_u.mutation.ProviderBalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProviderBalancesTable,
			Columns: []string{fiatcurrency.ProviderBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerbalances.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderBalancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProviderBalancesTable,
			Columns: []string{fiatcurrency.ProviderBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerbalances.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProvisionBucketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProvisionBucketsTable,
			Columns: []string{fiatcurrency.ProvisionBucketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provisionbucket.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProvisionBucketsIDs(); len(nodes) > 0 && !_u.mutation.ProvisionBucketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProvisionBucketsTable,
			Columns: []string{fiatcurrency.ProvisionBucketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provisionbucket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProvisionBucketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProvisionBucketsTable,
			Columns: []string{fiatcurrency.ProvisionBucketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provisionbucket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InstitutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.InstitutionsTable,
			Columns: []string{fiatcurrency.InstitutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(institution.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstitutionsIDs(); len(nodes) > 0 && !_u.mutation.InstitutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.InstitutionsTable,
			Columns: []string{fiatcurrency.InstitutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(institution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstitutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.InstitutionsTable,
			Columns: []string{fiatcurrency.InstitutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(institution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProviderOrderTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProviderOrderTokensTable,
			Columns: []string{fiatcurrency.ProviderOrderTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerordertoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProviderOrderTokensIDs(); len(nodes) > 0 && !_u.mutation.ProviderOrderTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProviderOrderTokensTable,
			Columns: []string{fiatcurrency.ProviderOrderTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerordertoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderOrderTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fiatcurrency.ProviderOrderTokensTable,
			Columns: []string{fiatcurrency.ProviderOrderTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerordertoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FiatCurrency{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fiatcurrency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
