// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/paycrest/aggregator/ent/fiatcurrency"
	"github.com/paycrest/aggregator/ent/institution"
	"github.com/paycrest/aggregator/ent/predicate"
	"github.com/paycrest/aggregator/ent/providerbalances"
	"github.com/paycrest/aggregator/ent/providerordertoken"
	"github.com/paycrest/aggregator/ent/provisionbucket"
)

// FiatCurrencyQuery is the builder for querying FiatCurrency entities.
type FiatCurrencyQuery struct {
	config
	ctx                     *QueryContext
	order                   []fiatcurrency.OrderOption
	inters                  []Interceptor
	predicates              []predicate.FiatCurrency
	withProviderBalances    *ProviderBalancesQuery
	withProvisionBuckets    *ProvisionBucketQuery
	withInstitutions        *InstitutionQuery
	withProviderOrderTokens *ProviderOrderTokenQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FiatCurrencyQuery builder.
func (_q *FiatCurrencyQuery) Where(ps ...predicate.FiatCurrency) *FiatCurrencyQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *FiatCurrencyQuery) Limit(limit int) *FiatCurrencyQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *FiatCurrencyQuery) Offset(offset int) *FiatCurrencyQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *FiatCurrencyQuery) Unique(unique bool) *FiatCurrencyQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *FiatCurrencyQuery) Order(o ...fiatcurrency.OrderOption) *FiatCurrencyQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProviderBalances chains the current query on the "provider_balances" edge.
func (_q *FiatCurrencyQuery) QueryProviderBalances() *ProviderBalancesQuery {
	query := (&ProviderBalancesClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fiatcurrency.Table, fiatcurrency.FieldID, selector),
			sqlgraph.To(providerbalances.Table, providerbalances.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, fiatcurrency.ProviderBalancesTable, fiatcurrency.ProviderBalancesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProvisionBuckets chains the current query on the "provision_buckets" edge.
func (_q *FiatCurrencyQuery) QueryProvisionBuckets() *ProvisionBucketQuery {
	query := (&ProvisionBucketClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fiatcurrency.Table, fiatcurrency.FieldID, selector),
			sqlgraph.To(provisionbucket.Table, provisionbucket.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, fiatcurrency.ProvisionBucketsTable, fiatcurrency.ProvisionBucketsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInstitutions chains the current query on the "institutions" edge.
func (_q *FiatCurrencyQuery) QueryInstitutions() *InstitutionQuery {
	query := (&InstitutionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fiatcurrency.Table, fiatcurrency.FieldID, selector),
			sqlgraph.To(institution.Table, institution.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, fiatcurrency.InstitutionsTable, fiatcurrency.InstitutionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProviderOrderTokens chains the current query on the "provider_order_tokens" edge.
func (_q *FiatCurrencyQuery) QueryProviderOrderTokens() *ProviderOrderTokenQuery {
	query := (&ProviderOrderTokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fiatcurrency.Table, fiatcurrency.FieldID, selector),
			sqlgraph.To(providerordertoken.Table, providerordertoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, fiatcurrency.ProviderOrderTokensTable, fiatcurrency.ProviderOrderTokensColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FiatCurrency entity from the query.
// Returns a *NotFoundError when no FiatCurrency was found.
func (_q *FiatCurrencyQuery) First(ctx context.Context) (*FiatCurrency, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fiatcurrency.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *FiatCurrencyQuery) FirstX(ctx context.Context) *FiatCurrency {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FiatCurrency ID from the query.
// Returns a *NotFoundError when no FiatCurrency ID was found.
func (_q *FiatCurrencyQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fiatcurrency.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *FiatCurrencyQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FiatCurrency entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FiatCurrency entity is found.
// Returns a *NotFoundError when no FiatCurrency entities are found.
func (_q *FiatCurrencyQuery) Only(ctx context.Context) (*FiatCurrency, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fiatcurrency.Label}
	default:
		return nil, &NotSingularError{fiatcurrency.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *FiatCurrencyQuery) OnlyX(ctx context.Context) *FiatCurrency {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FiatCurrency ID in the query.
// Returns a *NotSingularError when more than one FiatCurrency ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *FiatCurrencyQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fiatcurrency.Label}
	default:
		err = &NotSingularError{fiatcurrency.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *FiatCurrencyQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FiatCurrencies.
func (_q *FiatCurrencyQuery) All(ctx context.Context) ([]*FiatCurrency, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FiatCurrency, *FiatCurrencyQuery]()
	return withInterceptors[[]*FiatCurrency](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *FiatCurrencyQuery) AllX(ctx context.Context) []*FiatCurrency {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FiatCurrency IDs.
func (_q *FiatCurrencyQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(fiatcurrency.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *FiatCurrencyQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *FiatCurrencyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*FiatCurrencyQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *FiatCurrencyQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *FiatCurrencyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *FiatCurrencyQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FiatCurrencyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *FiatCurrencyQuery) Clone() *FiatCurrencyQuery {
	if _q == nil {
		return nil
	}
	return &FiatCurrencyQuery{
		config:                  _q.config,
		ctx:                     _q.ctx.Clone(),
		order:                   append([]fiatcurrency.OrderOption{}, _q.order...),
		inters:                  append([]Interceptor{}, _q.inters...),
		predicates:              append([]predicate.FiatCurrency{}, _q.predicates...),
		withProviderBalances:    _q.withProviderBalances.Clone(),
		withProvisionBuckets:    _q.withProvisionBuckets.Clone(),
		withInstitutions:        _q.withInstitutions.Clone(),
		withProviderOrderTokens: _q.withProviderOrderTokens.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProviderBalances tells the query-builder to eager-load the nodes that are connected to
// the "provider_balances" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FiatCurrencyQuery) WithProviderBalances(opts ...func(*ProviderBalancesQuery)) *FiatCurrencyQuery {
	query := (&ProviderBalancesClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProviderBalances = query
	return _q
}

// WithProvisionBuckets tells the query-builder to eager-load the nodes that are connected to
// the "provision_buckets" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FiatCurrencyQuery) WithProvisionBuckets(opts ...func(*ProvisionBucketQuery)) *FiatCurrencyQuery {
	query := (&ProvisionBucketClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProvisionBuckets = query
	return _q
}

// WithInstitutions tells the query-builder to eager-load the nodes that are connected to
// the "institutions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FiatCurrencyQuery) WithInstitutions(opts ...func(*InstitutionQuery)) *FiatCurrencyQuery {
	query := (&InstitutionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInstitutions = query
	return _q
}

// WithProviderOrderTokens tells the query-builder to eager-load the nodes that are connected to
// the "provider_order_tokens" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FiatCurrencyQuery) WithProviderOrderTokens(opts ...func(*ProviderOrderTokenQuery)) *FiatCurrencyQuery {
	query := (&ProviderOrderTokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProviderOrderTokens = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FiatCurrency.Query().
//		GroupBy(fiatcurrency.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *FiatCurrencyQuery) GroupBy(field string, fields ...string) *FiatCurrencyGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FiatCurrencyGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = fiatcurrency.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.FiatCurrency.Query().
//		Select(fiatcurrency.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *FiatCurrencyQuery) Select(fields ...string) *FiatCurrencySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &FiatCurrencySelect{FiatCurrencyQuery: _q}
	sbuild.label = fiatcurrency.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FiatCurrencySelect configured with the given aggregations.
func (_q *FiatCurrencyQuery) Aggregate(fns ...AggregateFunc) *FiatCurrencySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *FiatCurrencyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !fiatcurrency.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *FiatCurrencyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FiatCurrency, error) {
	var (
		nodes       = []*FiatCurrency{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withProviderBalances != nil,
			_q.withProvisionBuckets != nil,
			_q.withInstitutions != nil,
			_q.withProviderOrderTokens != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FiatCurrency).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FiatCurrency{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProviderBalances; query != nil {
		if err := _q.loadProviderBalances(ctx, query, nodes,
			func(n *FiatCurrency) { n.Edges.ProviderBalances = []*ProviderBalances{} },
			func(n *FiatCurrency, e *ProviderBalances) {
				n.Edges.ProviderBalances = append(n.Edges.ProviderBalances, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withProvisionBuckets; query != nil {
		if err := _q.loadProvisionBuckets(ctx, query, nodes,
			func(n *FiatCurrency) { n.Edges.ProvisionBuckets = []*ProvisionBucket{} },
			func(n *FiatCurrency, e *ProvisionBucket) {
				n.Edges.ProvisionBuckets = append(n.Edges.ProvisionBuckets, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withInstitutions; query != nil {
		if err := _q.loadInstitutions(ctx, query, nodes,
			func(n *FiatCurrency) { n.Edges.Institutions = []*Institution{} },
			func(n *FiatCurrency, e *Institution) { n.Edges.Institutions = append(n.Edges.Institutions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProviderOrderTokens; query != nil {
		if err := _q.loadProviderOrderTokens(ctx, query, nodes,
			func(n *FiatCurrency) { n.Edges.ProviderOrderTokens = []*ProviderOrderToken{} },
			func(n *FiatCurrency, e *ProviderOrderToken) {
				n.Edges.ProviderOrderTokens = append(n.Edges.ProviderOrderTokens, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *FiatCurrencyQuery) loadProviderBalances(ctx context.Context, query *ProviderBalancesQuery, nodes []*FiatCurrency, init func(*FiatCurrency), assign func(*FiatCurrency, *ProviderBalances)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*FiatCurrency)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ProviderBalances(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(fiatcurrency.ProviderBalancesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.fiat_currency_provider_balances
		if fk == nil {
			return fmt.Errorf(`foreign-key "fiat_currency_provider_balances" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "fiat_currency_provider_balances" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *FiatCurrencyQuery) loadProvisionBuckets(ctx context.Context, query *ProvisionBucketQuery, nodes []*FiatCurrency, init func(*FiatCurrency), assign func(*FiatCurrency, *ProvisionBucket)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*FiatCurrency)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ProvisionBucket(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(fiatcurrency.ProvisionBucketsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.fiat_currency_provision_buckets
		if fk == nil {
			return fmt.Errorf(`foreign-key "fiat_currency_provision_buckets" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "fiat_currency_provision_buckets" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *FiatCurrencyQuery) loadInstitutions(ctx context.Context, query *InstitutionQuery, nodes []*FiatCurrency, init func(*FiatCurrency), assign func(*FiatCurrency, *Institution)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*FiatCurrency)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Institution(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(fiatcurrency.InstitutionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.fiat_currency_institutions
		if fk == nil {
			return fmt.Errorf(`foreign-key "fiat_currency_institutions" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "fiat_currency_institutions" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *FiatCurrencyQuery) loadProviderOrderTokens(ctx context.Context, query *ProviderOrderTokenQuery, nodes []*FiatCurrency, init func(*FiatCurrency), assign func(*FiatCurrency, *ProviderOrderToken)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*FiatCurrency)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ProviderOrderToken(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(fiatcurrency.ProviderOrderTokensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.fiat_currency_provider_order_tokens
		if fk == nil {
			return fmt.Errorf(`foreign-key "fiat_currency_provider_order_tokens" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "fiat_currency_provider_order_tokens" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *FiatCurrencyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *FiatCurrencyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(fiatcurrency.Table, fiatcurrency.Columns, sqlgraph.NewFieldSpec(fiatcurrency.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fiatcurrency.FieldID)
		for i := range fields {
			if fields[i] != fiatcurrency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *FiatCurrencyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(fiatcurrency.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = fiatcurrency.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FiatCurrencyGroupBy is the group-by builder for FiatCurrency entities.
type FiatCurrencyGroupBy struct {
	selector
	build *FiatCurrencyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *FiatCurrencyGroupBy) Aggregate(fns ...AggregateFunc) *FiatCurrencyGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *FiatCurrencyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FiatCurrencyQuery, *FiatCurrencyGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *FiatCurrencyGroupBy) sqlScan(ctx context.Context, root *FiatCurrencyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FiatCurrencySelect is the builder for selecting fields of FiatCurrency entities.
type FiatCurrencySelect struct {
	*FiatCurrencyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *FiatCurrencySelect) Aggregate(fns ...AggregateFunc) *FiatCurrencySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *FiatCurrencySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FiatCurrencyQuery, *FiatCurrencySelect](ctx, _s.FiatCurrencyQuery, _s, _s.inters, v)
}

func (_s *FiatCurrencySelect) sqlScan(ctx context.Context, root *FiatCurrencyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
