// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/paycrest/aggregator/ent/lockpaymentorder"
	"github.com/paycrest/aggregator/ent/providerprofile"
	"github.com/paycrest/aggregator/ent/provisionbucket"
	"github.com/paycrest/aggregator/ent/token"
	"github.com/shopspring/decimal"
)

// LockPaymentOrder is the model entity for the LockPaymentOrder schema.
type LockPaymentOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GatewayID holds the value of the "gateway_id" field.
	GatewayID string `json:"gateway_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount decimal.Decimal `json:"amount,omitempty"`
	// ProtocolFee holds the value of the "protocol_fee" field.
	ProtocolFee decimal.Decimal `json:"protocol_fee,omitempty"`
	// Rate holds the value of the "rate" field.
	Rate decimal.Decimal `json:"rate,omitempty"`
	// OrderPercent holds the value of the "order_percent" field.
	OrderPercent decimal.Decimal `json:"order_percent,omitempty"`
	// Sender holds the value of the "sender" field.
	Sender string `json:"sender,omitempty"`
	// TxHash holds the value of the "tx_hash" field.
	TxHash string `json:"tx_hash,omitempty"`
	// Status holds the value of the "status" field.
	Status lockpaymentorder.Status `json:"status,omitempty"`
	// BlockNumber holds the value of the "block_number" field.
	BlockNumber int64 `json:"block_number,omitempty"`
	// Institution holds the value of the "institution" field.
	Institution string `json:"institution,omitempty"`
	// AccountIdentifier holds the value of the "account_identifier" field.
	AccountIdentifier string `json:"account_identifier,omitempty"`
	// AccountName holds the value of the "account_name" field.
	AccountName string `json:"account_name,omitempty"`
	// Memo holds the value of the "memo" field.
	Memo string `json:"memo,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CancellationCount holds the value of the "cancellation_count" field.
	CancellationCount int `json:"cancellation_count,omitempty"`
	// CancellationReasons holds the value of the "cancellation_reasons" field.
	CancellationReasons []string `json:"cancellation_reasons,omitempty"`
	// MessageHash holds the value of the "message_hash" field.
	MessageHash string `json:"message_hash,omitempty"`
	// AmountInUsd holds the value of the "amount_in_usd" field.
	AmountInUsd decimal.Decimal `json:"amount_in_usd,omitempty"`
	// OrderType holds the value of the "order_type" field.
	OrderType lockpaymentorder.OrderType `json:"order_type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LockPaymentOrderQuery when eager-loading is set.
	Edges                                LockPaymentOrderEdges `json:"edges"`
	provider_profile_assigned_orders     *string
	provision_bucket_lock_payment_orders *int
	token_lock_payment_orders            *int
	selectValues                         sql.SelectValues
}

// LockPaymentOrderEdges holds the relations/edges for other nodes in the graph.
type LockPaymentOrderEdges struct {
	// Token holds the value of the token edge.
	Token *Token `json:"token,omitempty"`
	// ProvisionBucket holds the value of the provision_bucket edge.
	ProvisionBucket *ProvisionBucket `json:"provision_bucket,omitempty"`
	// Provider holds the value of the provider edge.
	Provider *ProviderProfile `json:"provider,omitempty"`
	// Fulfillments holds the value of the fulfillments edge.
	Fulfillments []*LockOrderFulfillment `json:"fulfillments,omitempty"`
	// Transactions holds the value of the transactions edge.
	Transactions []*TransactionLog `json:"transactions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// TokenOrErr returns the Token value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LockPaymentOrderEdges) TokenOrErr() (*Token, error) {
	if e.Token != nil {
		return e.Token, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: token.Label}
	}
	return nil, &NotLoadedError{edge: "token"}
}

// ProvisionBucketOrErr returns the ProvisionBucket value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LockPaymentOrderEdges) ProvisionBucketOrErr() (*ProvisionBucket, error) {
	if e.ProvisionBucket != nil {
		return e.ProvisionBucket, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: provisionbucket.Label}
	}
	return nil, &NotLoadedError{edge: "provision_bucket"}
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LockPaymentOrderEdges) ProviderOrErr() (*ProviderProfile, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: providerprofile.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// FulfillmentsOrErr returns the Fulfillments value or an error if the edge
// was not loaded in eager-loading.
func (e LockPaymentOrderEdges) FulfillmentsOrErr() ([]*LockOrderFulfillment, error) {
	if e.loadedTypes[3] {
		return e.Fulfillments, nil
	}
	return nil, &NotLoadedError{edge: "fulfillments"}
}

// TransactionsOrErr returns the Transactions value or an error if the edge
// was not loaded in eager-loading.
func (e LockPaymentOrderEdges) TransactionsOrErr() ([]*TransactionLog, error) {
	if e.loadedTypes[4] {
		return e.Transactions, nil
	}
	return nil, &NotLoadedError{edge: "transactions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LockPaymentOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lockpaymentorder.FieldMetadata, lockpaymentorder.FieldCancellationReasons:
			values[i] = new([]byte)
		case lockpaymentorder.FieldAmount, lockpaymentorder.FieldProtocolFee, lockpaymentorder.FieldRate, lockpaymentorder.FieldOrderPercent, lockpaymentorder.FieldAmountInUsd:
			values[i] = new(decimal.Decimal)
		case lockpaymentorder.FieldBlockNumber, lockpaymentorder.FieldCancellationCount:
			values[i] = new(sql.NullInt64)
		case lockpaymentorder.FieldGatewayID, lockpaymentorder.FieldSender, lockpaymentorder.FieldTxHash, lockpaymentorder.FieldStatus, lockpaymentorder.FieldInstitution, lockpaymentorder.FieldAccountIdentifier, lockpaymentorder.FieldAccountName, lockpaymentorder.FieldMemo, lockpaymentorder.FieldMessageHash, lockpaymentorder.FieldOrderType:
			values[i] = new(sql.NullString)
		case lockpaymentorder.FieldCreatedAt, lockpaymentorder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case lockpaymentorder.FieldID:
			values[i] = new(uuid.UUID)
		case lockpaymentorder.ForeignKeys[0]: // provider_profile_assigned_orders
			values[i] = new(sql.NullString)
		case lockpaymentorder.ForeignKeys[1]: // provision_bucket_lock_payment_orders
			values[i] = new(sql.NullInt64)
		case lockpaymentorder.ForeignKeys[2]: // token_lock_payment_orders
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LockPaymentOrder fields.
func (_m *LockPaymentOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lockpaymentorder.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case lockpaymentorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case lockpaymentorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case lockpaymentorder.FieldGatewayID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_id", values[i])
			} else if value.Valid {
				_m.GatewayID = value.String
			}
		case lockpaymentorder.FieldAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value != nil {
				_m.Amount = *value
			}
		case lockpaymentorder.FieldProtocolFee:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field protocol_fee", values[i])
			} else if value != nil {
				_m.ProtocolFee = *value
			}
		case lockpaymentorder.FieldRate:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value != nil {
				_m.Rate = *value
			}
		case lockpaymentorder.FieldOrderPercent:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field order_percent", values[i])
			} else if value != nil {
				_m.OrderPercent = *value
			}
		case lockpaymentorder.FieldSender:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender", values[i])
			} else if value.Valid {
				_m.Sender = value.String
			}
		case lockpaymentorder.FieldTxHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tx_hash", values[i])
			} else if value.Valid {
				_m.TxHash = value.String
			}
		case lockpaymentorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = lockpaymentorder.Status(value.String)
			}
		case lockpaymentorder.FieldBlockNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field block_number", values[i])
			} else if value.Valid {
				_m.BlockNumber = value.Int64
			}
		case lockpaymentorder.FieldInstitution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field institution", values[i])
			} else if value.Valid {
				_m.Institution = value.String
			}
		case lockpaymentorder.FieldAccountIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_identifier", values[i])
			} else if value.Valid {
				_m.AccountIdentifier = value.String
			}
		case lockpaymentorder.FieldAccountName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_name", values[i])
			} else if value.Valid {
				_m.AccountName = value.String
			}
		case lockpaymentorder.FieldMemo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field memo", values[i])
			} else if value.Valid {
				_m.Memo = value.String
			}
		case lockpaymentorder.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case lockpaymentorder.FieldCancellationCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cancellation_count", values[i])
			} else if value.Valid {
				_m.CancellationCount = int(value.Int64)
			}
		case lockpaymentorder.FieldCancellationReasons:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field cancellation_reasons", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CancellationReasons); err != nil {
					return fmt.Errorf("unmarshal field cancellation_reasons: %w", err)
				}
			}
		case lockpaymentorder.FieldMessageHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_hash", values[i])
			} else if value.Valid {
				_m.MessageHash = value.String
			}
		case lockpaymentorder.FieldAmountInUsd:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount_in_usd", values[i])
			} else if value != nil {
				_m.AmountInUsd = *value
			}
		case lockpaymentorder.FieldOrderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_type", values[i])
			} else if value.Valid {
				_m.OrderType = lockpaymentorder.OrderType(value.String)
			}
		case lockpaymentorder.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_profile_assigned_orders", values[i])
			} else if value.Valid {
				_m.provider_profile_assigned_orders = new(string)
				*_m.provider_profile_assigned_orders = value.String
			}
		case lockpaymentorder.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field provision_bucket_lock_payment_orders", value)
			} else if value.Valid {
				_m.provision_bucket_lock_payment_orders = new(int)
				*_m.provision_bucket_lock_payment_orders = int(value.Int64)
			}
		case lockpaymentorder.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field token_lock_payment_orders", value)
			} else if value.Valid {
				_m.token_lock_payment_orders = new(int)
				*_m.token_lock_payment_orders = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LockPaymentOrder.
// This includes values selected through modifiers, order, etc.
func (_m *LockPaymentOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryToken queries the "token" edge of the LockPaymentOrder entity.
func (_m *LockPaymentOrder) QueryToken() *TokenQuery {
	return NewLockPaymentOrderClient(_m.config).QueryToken(_m)
}

// QueryProvisionBucket queries the "provision_bucket" edge of the LockPaymentOrder entity.
func (_m *LockPaymentOrder) QueryProvisionBucket() *ProvisionBucketQuery {
	return NewLockPaymentOrderClient(_m.config).QueryProvisionBucket(_m)
}

// QueryProvider queries the "provider" edge of the LockPaymentOrder entity.
func (_m *LockPaymentOrder) QueryProvider() *ProviderProfileQuery {
	return NewLockPaymentOrderClient(_m.config).QueryProvider(_m)
}

// QueryFulfillments queries the "fulfillments" edge of the LockPaymentOrder entity.
func (_m *LockPaymentOrder) QueryFulfillments() *LockOrderFulfillmentQuery {
	return NewLockPaymentOrderClient(_m.config).QueryFulfillments(_m)
}

// QueryTransactions queries the "transactions" edge of the LockPaymentOrder entity.
func (_m *LockPaymentOrder) QueryTransactions() *TransactionLogQuery {
	return NewLockPaymentOrderClient(_m.config).QueryTransactions(_m)
}

// Update returns a builder for updating this LockPaymentOrder.
// Note that you need to call LockPaymentOrder.Unwrap() before calling this method if this LockPaymentOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LockPaymentOrder) Update() *LockPaymentOrderUpdateOne {
	return NewLockPaymentOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LockPaymentOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LockPaymentOrder) Unwrap() *LockPaymentOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LockPaymentOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LockPaymentOrder) String() string {
	var builder strings.Builder
	builder.WriteString("LockPaymentOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("gateway_id=")
	builder.WriteString(_m.GatewayID)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("protocol_fee=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProtocolFee))
	builder.WriteString(", ")
	builder.WriteString("rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rate))
	builder.WriteString(", ")
	builder.WriteString("order_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderPercent))
	builder.WriteString(", ")
	builder.WriteString("sender=")
	builder.WriteString(_m.Sender)
	builder.WriteString(", ")
	builder.WriteString("tx_hash=")
	builder.WriteString(_m.TxHash)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("block_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.BlockNumber))
	builder.WriteString(", ")
	builder.WriteString("institution=")
	builder.WriteString(_m.Institution)
	builder.WriteString(", ")
	builder.WriteString("account_identifier=")
	builder.WriteString(_m.AccountIdentifier)
	builder.WriteString(", ")
	builder.WriteString("account_name=")
	builder.WriteString(_m.AccountName)
	builder.WriteString(", ")
	builder.WriteString("memo=")
	builder.WriteString(_m.Memo)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("cancellation_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CancellationCount))
	builder.WriteString(", ")
	builder.WriteString("cancellation_reasons=")
	builder.WriteString(fmt.Sprintf("%v", _m.CancellationReasons))
	builder.WriteString(", ")
	builder.WriteString("message_hash=")
	builder.WriteString(_m.MessageHash)
	builder.WriteString(", ")
	builder.WriteString("amount_in_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountInUsd))
	builder.WriteString(", ")
	builder.WriteString("order_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderType))
	builder.WriteByte(')')
	return builder.String()
}

// LockPaymentOrders is a parsable slice of LockPaymentOrder.
type LockPaymentOrders []*LockPaymentOrder
