// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/paycrest/aggregator/ent/paymentorder"
	"github.com/paycrest/aggregator/ent/paymentorderfulfillment"
)

// PaymentOrderFulfillmentCreate is the builder for creating a PaymentOrderFulfillment entity.
type PaymentOrderFulfillmentCreate struct {
	config
	mutation *PaymentOrderFulfillmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (pofc *PaymentOrderFulfillmentCreate) SetCreatedAt(t time.Time) *PaymentOrderFulfillmentCreate {
	pofc.mutation.SetCreatedAt(t)
	return pofc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pofc *PaymentOrderFulfillmentCreate) SetNillableCreatedAt(t *time.Time) *PaymentOrderFulfillmentCreate {
	if t != nil {
		pofc.SetCreatedAt(*t)
	}
	return pofc
}

// SetUpdatedAt sets the "updated_at" field.
func (pofc *PaymentOrderFulfillmentCreate) SetUpdatedAt(t time.Time) *PaymentOrderFulfillmentCreate {
	pofc.mutation.SetUpdatedAt(t)
	return pofc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pofc *PaymentOrderFulfillmentCreate) SetNillableUpdatedAt(t *time.Time) *PaymentOrderFulfillmentCreate {
	if t != nil {
		pofc.SetUpdatedAt(*t)
	}
	return pofc
}

// SetTxID sets the "tx_id" field.
func (pofc *PaymentOrderFulfillmentCreate) SetTxID(s string) *PaymentOrderFulfillmentCreate {
	pofc.mutation.SetTxID(s)
	return pofc
}

// SetNillableTxID sets the "tx_id" field if the given value is not nil.
func (pofc *PaymentOrderFulfillmentCreate) SetNillableTxID(s *string) *PaymentOrderFulfillmentCreate {
	if s != nil {
		pofc.SetTxID(*s)
	}
	return pofc
}

// SetPsp sets the "psp" field.
func (pofc *PaymentOrderFulfillmentCreate) SetPsp(s string) *PaymentOrderFulfillmentCreate {
	pofc.mutation.SetPsp(s)
	return pofc
}

// SetNillablePsp sets the "psp" field if the given value is not nil.
func (pofc *PaymentOrderFulfillmentCreate) SetNillablePsp(s *string) *PaymentOrderFulfillmentCreate {
	if s != nil {
		pofc.SetPsp(*s)
	}
	return pofc
}

// SetValidationStatus sets the "validation_status" field.
func (pofc *PaymentOrderFulfillmentCreate) SetValidationStatus(ps paymentorderfulfillment.ValidationStatus) *PaymentOrderFulfillmentCreate {
	pofc.mutation.SetValidationStatus(ps)
	return pofc
}

// SetNillableValidationStatus sets the "validation_status" field if the given value is not nil.
func (pofc *PaymentOrderFulfillmentCreate) SetNillableValidationStatus(ps *paymentorderfulfillment.ValidationStatus) *PaymentOrderFulfillmentCreate {
	if ps != nil {
		pofc.SetValidationStatus(*ps)
	}
	return pofc
}

// SetValidationError sets the "validation_error" field.
func (pofc *PaymentOrderFulfillmentCreate) SetValidationError(s string) *PaymentOrderFulfillmentCreate {
	pofc.mutation.SetValidationError(s)
	return pofc
}

// SetNillableValidationError sets the "validation_error" field if the given value is not nil.
func (pofc *PaymentOrderFulfillmentCreate) SetNillableValidationError(s *string) *PaymentOrderFulfillmentCreate {
	if s != nil {
		pofc.SetValidationError(*s)
	}
	return pofc
}

// SetID sets the "id" field.
func (pofc *PaymentOrderFulfillmentCreate) SetID(u uuid.UUID) *PaymentOrderFulfillmentCreate {
	pofc.mutation.SetID(u)
	return pofc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pofc *PaymentOrderFulfillmentCreate) SetNillableID(u *uuid.UUID) *PaymentOrderFulfillmentCreate {
	if u != nil {
		pofc.SetID(*u)
	}
	return pofc
}

// SetOrderID sets the "order" edge to the PaymentOrder entity by ID.
func (pofc *PaymentOrderFulfillmentCreate) SetOrderID(id uuid.UUID) *PaymentOrderFulfillmentCreate {
	pofc.mutation.SetOrderID(id)
	return pofc
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (pofc *PaymentOrderFulfillmentCreate) SetOrder(p *PaymentOrder) *PaymentOrderFulfillmentCreate {
	return pofc.SetOrderID(p.ID)
}

// Mutation returns the PaymentOrderFulfillmentMutation object of the builder.
func (pofc *PaymentOrderFulfillmentCreate) Mutation() *PaymentOrderFulfillmentMutation {
	return pofc.mutation
}

// Save creates the PaymentOrderFulfillment in the database.
func (pofc *PaymentOrderFulfillmentCreate) Save(ctx context.Context) (*PaymentOrderFulfillment, error) {
	pofc.defaults()
	return withHooks(ctx, pofc.sqlSave, pofc.mutation, pofc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pofc *PaymentOrderFulfillmentCreate) SaveX(ctx context.Context) *PaymentOrderFulfillment {
	v, err := pofc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pofc *PaymentOrderFulfillmentCreate) Exec(ctx context.Context) error {
	_, err := pofc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pofc *PaymentOrderFulfillmentCreate) ExecX(ctx context.Context) {
	if err := pofc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pofc *PaymentOrderFulfillmentCreate) defaults() {
	if _, ok := pofc.mutation.CreatedAt(); !ok {
		v := paymentorderfulfillment.DefaultCreatedAt()
		pofc.mutation.SetCreatedAt(v)
	}
	if _, ok := pofc.mutation.UpdatedAt(); !ok {
		v := paymentorderfulfillment.DefaultUpdatedAt()
		pofc.mutation.SetUpdatedAt(v)
	}
	if _, ok := pofc.mutation.ValidationStatus(); !ok {
		v := paymentorderfulfillment.DefaultValidationStatus
		pofc.mutation.SetValidationStatus(v)
	}
	if _, ok := pofc.mutation.ID(); !ok {
		v := paymentorderfulfillment.DefaultID()
		pofc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pofc *PaymentOrderFulfillmentCreate) check() error {
	if _, ok := pofc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentOrderFulfillment.created_at"`)}
	}
	if _, ok := pofc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentOrderFulfillment.updated_at"`)}
	}
	if _, ok := pofc.mutation.ValidationStatus(); !ok {
		return &ValidationError{Name: "validation_status", err: errors.New(`ent: missing required field "PaymentOrderFulfillment.validation_status"`)}
	}
	if v, ok := pofc.mutation.ValidationStatus(); ok {
		if err := paymentorderfulfillment.ValidationStatusValidator(v); err != nil {
			return &ValidationError{Name: "validation_status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrderFulfillment.validation_status": %w`, err)}
		}
	}
	if len(pofc.mutation.OrderIDs()) == 0 {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required edge "PaymentOrderFulfillment.order"`)}
	}
	return nil
}

func (pofc *PaymentOrderFulfillmentCreate) sqlSave(ctx context.Context) (*PaymentOrderFulfillment, error) {
	if err := pofc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pofc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pofc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pofc.mutation.id = &_node.ID
	pofc.mutation.done = true
	return _node, nil
}

func (pofc *PaymentOrderFulfillmentCreate) createSpec() (*PaymentOrderFulfillment, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentOrderFulfillment{config: pofc.config}
		_spec = sqlgraph.NewCreateSpec(paymentorderfulfillment.Table, sqlgraph.NewFieldSpec(paymentorderfulfillment.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = pofc.conflict
	if id, ok := pofc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pofc.mutation.CreatedAt(); ok {
		_spec.SetField(paymentorderfulfillment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pofc.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorderfulfillment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := pofc.mutation.TxID(); ok {
		_spec.SetField(paymentorderfulfillment.FieldTxID, field.TypeString, value)
		_node.TxID = value
	}
	if value, ok := pofc.mutation.Psp(); ok {
		_spec.SetField(paymentorderfulfillment.FieldPsp, field.TypeString, value)
		_node.Psp = value
	}
	if value, ok := pofc.mutation.ValidationStatus(); ok {
		_spec.SetField(paymentorderfulfillment.FieldValidationStatus, field.TypeEnum, value)
		_node.ValidationStatus = value
	}
	if value, ok := pofc.mutation.ValidationError(); ok {
		_spec.SetField(paymentorderfulfillment.FieldValidationError, field.TypeString, value)
		_node.ValidationError = value
	}
	if nodes := pofc.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorderfulfillment.OrderTable,
			Columns: []string{paymentorderfulfillment.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.payment_order_fulfillments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrderFulfillment.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderFulfillmentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (pofc *PaymentOrderFulfillmentCreate) OnConflict(opts ...sql.ConflictOption) *PaymentOrderFulfillmentUpsertOne {
	pofc.conflict = opts
	return &PaymentOrderFulfillmentUpsertOne{
		create: pofc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrderFulfillment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pofc *PaymentOrderFulfillmentCreate) OnConflictColumns(columns ...string) *PaymentOrderFulfillmentUpsertOne {
	pofc.conflict = append(pofc.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderFulfillmentUpsertOne{
		create: pofc,
	}
}

type (
	// PaymentOrderFulfillmentUpsertOne is the builder for "upsert"-ing
	//  one PaymentOrderFulfillment node.
	PaymentOrderFulfillmentUpsertOne struct {
		create *PaymentOrderFulfillmentCreate
	}

	// PaymentOrderFulfillmentUpsert is the "OnConflict" setter.
	PaymentOrderFulfillmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderFulfillmentUpsert) SetUpdatedAt(v time.Time) *PaymentOrderFulfillmentUpsert {
	u.Set(paymentorderfulfillment.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsert) UpdateUpdatedAt() *PaymentOrderFulfillmentUpsert {
	u.SetExcluded(paymentorderfulfillment.FieldUpdatedAt)
	return u
}

// SetTxID sets the "tx_id" field.
func (u *PaymentOrderFulfillmentUpsert) SetTxID(v string) *PaymentOrderFulfillmentUpsert {
	u.Set(paymentorderfulfillment.FieldTxID, v)
	return u
}

// UpdateTxID sets the "tx_id" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsert) UpdateTxID() *PaymentOrderFulfillmentUpsert {
	u.SetExcluded(paymentorderfulfillment.FieldTxID)
	return u
}

// ClearTxID clears the value of the "tx_id" field.
func (u *PaymentOrderFulfillmentUpsert) ClearTxID() *PaymentOrderFulfillmentUpsert {
	u.SetNull(paymentorderfulfillment.FieldTxID)
	return u
}

// SetPsp sets the "psp" field.
func (u *PaymentOrderFulfillmentUpsert) SetPsp(v string) *PaymentOrderFulfillmentUpsert {
	u.Set(paymentorderfulfillment.FieldPsp, v)
	return u
}

// UpdatePsp sets the "psp" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsert) UpdatePsp() *PaymentOrderFulfillmentUpsert {
	u.SetExcluded(paymentorderfulfillment.FieldPsp)
	return u
}

// ClearPsp clears the value of the "psp" field.
func (u *PaymentOrderFulfillmentUpsert) ClearPsp() *PaymentOrderFulfillmentUpsert {
	u.SetNull(paymentorderfulfillment.FieldPsp)
	return u
}

// SetValidationStatus sets the "validation_status" field.
func (u *PaymentOrderFulfillmentUpsert) SetValidationStatus(v paymentorderfulfillment.ValidationStatus) *PaymentOrderFulfillmentUpsert {
	u.Set(paymentorderfulfillment.FieldValidationStatus, v)
	return u
}

// UpdateValidationStatus sets the "validation_status" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsert) UpdateValidationStatus() *PaymentOrderFulfillmentUpsert {
	u.SetExcluded(paymentorderfulfillment.FieldValidationStatus)
	return u
}

// SetValidationError sets the "validation_error" field.
func (u *PaymentOrderFulfillmentUpsert) SetValidationError(v string) *PaymentOrderFulfillmentUpsert {
	u.Set(paymentorderfulfillment.FieldValidationError, v)
	return u
}

// UpdateValidationError sets the "validation_error" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsert) UpdateValidationError() *PaymentOrderFulfillmentUpsert {
	u.SetExcluded(paymentorderfulfillment.FieldValidationError)
	return u
}

// ClearValidationError clears the value of the "validation_error" field.
func (u *PaymentOrderFulfillmentUpsert) ClearValidationError() *PaymentOrderFulfillmentUpsert {
	u.SetNull(paymentorderfulfillment.FieldValidationError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PaymentOrderFulfillment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(paymentorderfulfillment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PaymentOrderFulfillmentUpsertOne) UpdateNewValues() *PaymentOrderFulfillmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(paymentorderfulfillment.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentorderfulfillment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrderFulfillment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentOrderFulfillmentUpsertOne) Ignore() *PaymentOrderFulfillmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderFulfillmentUpsertOne) DoNothing() *PaymentOrderFulfillmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderFulfillmentCreate.OnConflict
// documentation for more info.
func (u *PaymentOrderFulfillmentUpsertOne) Update(set func(*PaymentOrderFulfillmentUpsert)) *PaymentOrderFulfillmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderFulfillmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderFulfillmentUpsertOne) SetUpdatedAt(v time.Time) *PaymentOrderFulfillmentUpsertOne {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsertOne) UpdateUpdatedAt() *PaymentOrderFulfillmentUpsertOne {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTxID sets the "tx_id" field.
func (u *PaymentOrderFulfillmentUpsertOne) SetTxID(v string) *PaymentOrderFulfillmentUpsertOne {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.SetTxID(v)
	})
}

// UpdateTxID sets the "tx_id" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsertOne) UpdateTxID() *PaymentOrderFulfillmentUpsertOne {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.UpdateTxID()
	})
}

// ClearTxID clears the value of the "tx_id" field.
func (u *PaymentOrderFulfillmentUpsertOne) ClearTxID() *PaymentOrderFulfillmentUpsertOne {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.ClearTxID()
	})
}

// SetPsp sets the "psp" field.
func (u *PaymentOrderFulfillmentUpsertOne) SetPsp(v string) *PaymentOrderFulfillmentUpsertOne {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.SetPsp(v)
	})
}

// UpdatePsp sets the "psp" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsertOne) UpdatePsp() *PaymentOrderFulfillmentUpsertOne {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.UpdatePsp()
	})
}

// ClearPsp clears the value of the "psp" field.
func (u *PaymentOrderFulfillmentUpsertOne) ClearPsp() *PaymentOrderFulfillmentUpsertOne {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.ClearPsp()
	})
}

// SetValidationStatus sets the "validation_status" field.
func (u *PaymentOrderFulfillmentUpsertOne) SetValidationStatus(v paymentorderfulfillment.ValidationStatus) *PaymentOrderFulfillmentUpsertOne {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.SetValidationStatus(v)
	})
}

// UpdateValidationStatus sets the "validation_status" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsertOne) UpdateValidationStatus() *PaymentOrderFulfillmentUpsertOne {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.UpdateValidationStatus()
	})
}

// SetValidationError sets the "validation_error" field.
func (u *PaymentOrderFulfillmentUpsertOne) SetValidationError(v string) *PaymentOrderFulfillmentUpsertOne {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.SetValidationError(v)
	})
}

// UpdateValidationError sets the "validation_error" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsertOne) UpdateValidationError() *PaymentOrderFulfillmentUpsertOne {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.UpdateValidationError()
	})
}

// ClearValidationError clears the value of the "validation_error" field.
func (u *PaymentOrderFulfillmentUpsertOne) ClearValidationError() *PaymentOrderFulfillmentUpsertOne {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.ClearValidationError()
	})
}

// Exec executes the query.
func (u *PaymentOrderFulfillmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderFulfillmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderFulfillmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentOrderFulfillmentUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PaymentOrderFulfillmentUpsertOne.ID is not supported by MySQL driver. Use PaymentOrderFulfillmentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentOrderFulfillmentUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentOrderFulfillmentCreateBulk is the builder for creating many PaymentOrderFulfillment entities in bulk.
type PaymentOrderFulfillmentCreateBulk struct {
	config
	err      error
	builders []*PaymentOrderFulfillmentCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentOrderFulfillment entities in the database.
func (pofcb *PaymentOrderFulfillmentCreateBulk) Save(ctx context.Context) ([]*PaymentOrderFulfillment, error) {
	if pofcb.err != nil {
		return nil, pofcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pofcb.builders))
	nodes := make([]*PaymentOrderFulfillment, len(pofcb.builders))
	mutators := make([]Mutator, len(pofcb.builders))
	for i := range pofcb.builders {
		func(i int, root context.Context) {
			builder := pofcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentOrderFulfillmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pofcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = pofcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pofcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pofcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pofcb *PaymentOrderFulfillmentCreateBulk) SaveX(ctx context.Context) []*PaymentOrderFulfillment {
	v, err := pofcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pofcb *PaymentOrderFulfillmentCreateBulk) Exec(ctx context.Context) error {
	_, err := pofcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pofcb *PaymentOrderFulfillmentCreateBulk) ExecX(ctx context.Context) {
	if err := pofcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrderFulfillment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderFulfillmentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (pofcb *PaymentOrderFulfillmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentOrderFulfillmentUpsertBulk {
	pofcb.conflict = opts
	return &PaymentOrderFulfillmentUpsertBulk{
		create: pofcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrderFulfillment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pofcb *PaymentOrderFulfillmentCreateBulk) OnConflictColumns(columns ...string) *PaymentOrderFulfillmentUpsertBulk {
	pofcb.conflict = append(pofcb.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderFulfillmentUpsertBulk{
		create: pofcb,
	}
}

// PaymentOrderFulfillmentUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentOrderFulfillment nodes.
type PaymentOrderFulfillmentUpsertBulk struct {
	create *PaymentOrderFulfillmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentOrderFulfillment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(paymentorderfulfillment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PaymentOrderFulfillmentUpsertBulk) UpdateNewValues() *PaymentOrderFulfillmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(paymentorderfulfillment.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentorderfulfillment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrderFulfillment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentOrderFulfillmentUpsertBulk) Ignore() *PaymentOrderFulfillmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderFulfillmentUpsertBulk) DoNothing() *PaymentOrderFulfillmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderFulfillmentCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentOrderFulfillmentUpsertBulk) Update(set func(*PaymentOrderFulfillmentUpsert)) *PaymentOrderFulfillmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderFulfillmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderFulfillmentUpsertBulk) SetUpdatedAt(v time.Time) *PaymentOrderFulfillmentUpsertBulk {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsertBulk) UpdateUpdatedAt() *PaymentOrderFulfillmentUpsertBulk {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTxID sets the "tx_id" field.
func (u *PaymentOrderFulfillmentUpsertBulk) SetTxID(v string) *PaymentOrderFulfillmentUpsertBulk {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.SetTxID(v)
	})
}

// UpdateTxID sets the "tx_id" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsertBulk) UpdateTxID() *PaymentOrderFulfillmentUpsertBulk {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.UpdateTxID()
	})
}

// ClearTxID clears the value of the "tx_id" field.
func (u *PaymentOrderFulfillmentUpsertBulk) ClearTxID() *PaymentOrderFulfillmentUpsertBulk {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.ClearTxID()
	})
}

// SetPsp sets the "psp" field.
func (u *PaymentOrderFulfillmentUpsertBulk) SetPsp(v string) *PaymentOrderFulfillmentUpsertBulk {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.SetPsp(v)
	})
}

// UpdatePsp sets the "psp" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsertBulk) UpdatePsp() *PaymentOrderFulfillmentUpsertBulk {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.UpdatePsp()
	})
}

// ClearPsp clears the value of the "psp" field.
func (u *PaymentOrderFulfillmentUpsertBulk) ClearPsp() *PaymentOrderFulfillmentUpsertBulk {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.ClearPsp()
	})
}

// SetValidationStatus sets the "validation_status" field.
func (u *PaymentOrderFulfillmentUpsertBulk) SetValidationStatus(v paymentorderfulfillment.ValidationStatus) *PaymentOrderFulfillmentUpsertBulk {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.SetValidationStatus(v)
	})
}

// UpdateValidationStatus sets the "validation_status" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsertBulk) UpdateValidationStatus() *PaymentOrderFulfillmentUpsertBulk {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.UpdateValidationStatus()
	})
}

// SetValidationError sets the "validation_error" field.
func (u *PaymentOrderFulfillmentUpsertBulk) SetValidationError(v string) *PaymentOrderFulfillmentUpsertBulk {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.SetValidationError(v)
	})
}

// UpdateValidationError sets the "validation_error" field to the value that was provided on create.
func (u *PaymentOrderFulfillmentUpsertBulk) UpdateValidationError() *PaymentOrderFulfillmentUpsertBulk {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.UpdateValidationError()
	})
}

// ClearValidationError clears the value of the "validation_error" field.
func (u *PaymentOrderFulfillmentUpsertBulk) ClearValidationError() *PaymentOrderFulfillmentUpsertBulk {
	return u.Update(func(s *PaymentOrderFulfillmentUpsert) {
		s.ClearValidationError()
	})
}

// Exec executes the query.
func (u *PaymentOrderFulfillmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentOrderFulfillmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderFulfillmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderFulfillmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
