// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/paycrest/aggregator/ent/paymentorderfulfillment"
	"github.com/paycrest/aggregator/ent/predicate"
)

// PaymentOrderFulfillmentDelete is the builder for deleting a PaymentOrderFulfillment entity.
type PaymentOrderFulfillmentDelete struct {
	config
	hooks    []Hook
	mutation *PaymentOrderFulfillmentMutation
}

// Where appends a list predicates to the PaymentOrderFulfillmentDelete builder.
func (pofd *PaymentOrderFulfillmentDelete) Where(ps ...predicate.PaymentOrderFulfillment) *PaymentOrderFulfillmentDelete {
	pofd.mutation.Where(ps...)
	return pofd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pofd *PaymentOrderFulfillmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pofd.sqlExec, pofd.mutation, pofd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pofd *PaymentOrderFulfillmentDelete) ExecX(ctx context.Context) int {
	n, err := pofd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pofd *PaymentOrderFulfillmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymentorderfulfillment.Table, sqlgraph.NewFieldSpec(paymentorderfulfillment.FieldID, field.TypeUUID))
	if ps := pofd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pofd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pofd.mutation.done = true
	return affected, err
}

// PaymentOrderFulfillmentDeleteOne is the builder for deleting a single PaymentOrderFulfillment entity.
type PaymentOrderFulfillmentDeleteOne struct {
	pofd *PaymentOrderFulfillmentDelete
}

// Where appends a list predicates to the PaymentOrderFulfillmentDelete builder.
func (pofdo *PaymentOrderFulfillmentDeleteOne) Where(ps ...predicate.PaymentOrderFulfillment) *PaymentOrderFulfillmentDeleteOne {
	pofdo.pofd.mutation.Where(ps...)
	return pofdo
}

// Exec executes the deletion query.
func (pofdo *PaymentOrderFulfillmentDeleteOne) Exec(ctx context.Context) error {
	n, err := pofdo.pofd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentorderfulfillment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pofdo *PaymentOrderFulfillmentDeleteOne) ExecX(ctx context.Context) {
	if err := pofdo.Exec(ctx); err != nil {
		panic(err)
	}
}
