// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/paycrest/aggregator/ent/linkedaddress"
	"github.com/paycrest/aggregator/ent/paymentorder"
	"github.com/paycrest/aggregator/ent/paymentorderrecipient"
	"github.com/paycrest/aggregator/ent/paymentwebhook"
	"github.com/paycrest/aggregator/ent/receiveaddress"
	"github.com/paycrest/aggregator/ent/senderprofile"
	"github.com/paycrest/aggregator/ent/token"
	"github.com/shopspring/decimal"
)

// PaymentOrder is the model entity for the PaymentOrder schema.
type PaymentOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount decimal.Decimal `json:"amount,omitempty"`
	// AmountPaid holds the value of the "amount_paid" field.
	AmountPaid decimal.Decimal `json:"amount_paid,omitempty"`
	// AmountReturned holds the value of the "amount_returned" field.
	AmountReturned decimal.Decimal `json:"amount_returned,omitempty"`
	// PercentSettled holds the value of the "percent_settled" field.
	PercentSettled decimal.Decimal `json:"percent_settled,omitempty"`
	// SenderFee holds the value of the "sender_fee" field.
	SenderFee decimal.Decimal `json:"sender_fee,omitempty"`
	// NetworkFee holds the value of the "network_fee" field.
	NetworkFee decimal.Decimal `json:"network_fee,omitempty"`
	// Rate holds the value of the "rate" field.
	Rate decimal.Decimal `json:"rate,omitempty"`
	// TxHash holds the value of the "tx_hash" field.
	TxHash string `json:"tx_hash,omitempty"`
	// BlockNumber holds the value of the "block_number" field.
	BlockNumber int64 `json:"block_number,omitempty"`
	// FromAddress holds the value of the "from_address" field.
	FromAddress string `json:"from_address,omitempty"`
	// ReturnAddress holds the value of the "return_address" field.
	ReturnAddress string `json:"return_address,omitempty"`
	// ReceiveAddressText holds the value of the "receive_address_text" field.
	ReceiveAddressText string `json:"receive_address_text,omitempty"`
	// FeePercent holds the value of the "fee_percent" field.
	FeePercent decimal.Decimal `json:"fee_percent,omitempty"`
	// FeeAddress holds the value of the "fee_address" field.
	FeeAddress string `json:"fee_address,omitempty"`
	// GatewayID holds the value of the "gateway_id" field.
	GatewayID string `json:"gateway_id,omitempty"`
	// MessageHash holds the value of the "message_hash" field.
	MessageHash string `json:"message_hash,omitempty"`
	// Reference holds the value of the "reference" field.
	Reference string `json:"reference,omitempty"`
	// Status holds the value of the "status" field.
	Status paymentorder.Status `json:"status,omitempty"`
	// AmountInUsd holds the value of the "amount_in_usd" field.
	AmountInUsd decimal.Decimal `json:"amount_in_usd,omitempty"`
	// OrderType holds the value of the "order_type" field.
	OrderType paymentorder.OrderType `json:"order_type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentOrderQuery when eager-loading is set.
	Edges                         PaymentOrderEdges `json:"edges"`
	api_key_payment_orders        *uuid.UUID
	linked_address_payment_orders *int
	sender_profile_payment_orders *uuid.UUID
	token_payment_orders          *int
	selectValues                  sql.SelectValues
}

// PaymentOrderEdges holds the relations/edges for other nodes in the graph.
type PaymentOrderEdges struct {
	// SenderProfile holds the value of the sender_profile edge.
	SenderProfile *SenderProfile `json:"sender_profile,omitempty"`
	// Token holds the value of the token edge.
	Token *Token `json:"token,omitempty"`
	// LinkedAddress holds the value of the linked_address edge.
	LinkedAddress *LinkedAddress `json:"linked_address,omitempty"`
	// ReceiveAddress holds the value of the receive_address edge.
	ReceiveAddress *ReceiveAddress `json:"receive_address,omitempty"`
	// Recipient holds the value of the recipient edge.
	Recipient *PaymentOrderRecipient `json:"recipient,omitempty"`
	// Transactions holds the value of the transactions edge.
	Transactions []*TransactionLog `json:"transactions,omitempty"`
	// PaymentWebhook holds the value of the payment_webhook edge.
	PaymentWebhook *PaymentWebhook `json:"payment_webhook,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// SenderProfileOrErr returns the SenderProfile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentOrderEdges) SenderProfileOrErr() (*SenderProfile, error) {
	if e.SenderProfile != nil {
		return e.SenderProfile, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: senderprofile.Label}
	}
	return nil, &NotLoadedError{edge: "sender_profile"}
}

// TokenOrErr returns the Token value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentOrderEdges) TokenOrErr() (*Token, error) {
	if e.Token != nil {
		return e.Token, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: token.Label}
	}
	return nil, &NotLoadedError{edge: "token"}
}

// LinkedAddressOrErr returns the LinkedAddress value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentOrderEdges) LinkedAddressOrErr() (*LinkedAddress, error) {
	if e.LinkedAddress != nil {
		return e.LinkedAddress, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: linkedaddress.Label}
	}
	return nil, &NotLoadedError{edge: "linked_address"}
}

// ReceiveAddressOrErr returns the ReceiveAddress value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentOrderEdges) ReceiveAddressOrErr() (*ReceiveAddress, error) {
	if e.ReceiveAddress != nil {
		return e.ReceiveAddress, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: receiveaddress.Label}
	}
	return nil, &NotLoadedError{edge: "receive_address"}
}

// RecipientOrErr returns the Recipient value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentOrderEdges) RecipientOrErr() (*PaymentOrderRecipient, error) {
	if e.Recipient != nil {
		return e.Recipient, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: paymentorderrecipient.Label}
	}
	return nil, &NotLoadedError{edge: "recipient"}
}

// TransactionsOrErr returns the Transactions value or an error if the edge
// was not loaded in eager-loading.
func (e PaymentOrderEdges) TransactionsOrErr() ([]*TransactionLog, error) {
	if e.loadedTypes[5] {
		return e.Transactions, nil
	}
	return nil, &NotLoadedError{edge: "transactions"}
}

// PaymentWebhookOrErr returns the PaymentWebhook value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentOrderEdges) PaymentWebhookOrErr() (*PaymentWebhook, error) {
	if e.PaymentWebhook != nil {
		return e.PaymentWebhook, nil
	} else if e.loadedTypes[6] {
		return nil, &NotFoundError{label: paymentwebhook.Label}
	}
	return nil, &NotLoadedError{edge: "payment_webhook"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentorder.FieldAmount, paymentorder.FieldAmountPaid, paymentorder.FieldAmountReturned, paymentorder.FieldPercentSettled, paymentorder.FieldSenderFee, paymentorder.FieldNetworkFee, paymentorder.FieldRate, paymentorder.FieldFeePercent, paymentorder.FieldAmountInUsd:
			values[i] = new(decimal.Decimal)
		case paymentorder.FieldBlockNumber:
			values[i] = new(sql.NullInt64)
		case paymentorder.FieldTxHash, paymentorder.FieldFromAddress, paymentorder.FieldReturnAddress, paymentorder.FieldReceiveAddressText, paymentorder.FieldFeeAddress, paymentorder.FieldGatewayID, paymentorder.FieldMessageHash, paymentorder.FieldReference, paymentorder.FieldStatus, paymentorder.FieldOrderType:
			values[i] = new(sql.NullString)
		case paymentorder.FieldCreatedAt, paymentorder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case paymentorder.FieldID:
			values[i] = new(uuid.UUID)
		case paymentorder.ForeignKeys[0]: // api_key_payment_orders
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case paymentorder.ForeignKeys[1]: // linked_address_payment_orders
			values[i] = new(sql.NullInt64)
		case paymentorder.ForeignKeys[2]: // sender_profile_payment_orders
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case paymentorder.ForeignKeys[3]: // token_payment_orders
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentOrder fields.
func (_m *PaymentOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentorder.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case paymentorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case paymentorder.FieldAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value != nil {
				_m.Amount = *value
			}
		case paymentorder.FieldAmountPaid:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount_paid", values[i])
			} else if value != nil {
				_m.AmountPaid = *value
			}
		case paymentorder.FieldAmountReturned:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount_returned", values[i])
			} else if value != nil {
				_m.AmountReturned = *value
			}
		case paymentorder.FieldPercentSettled:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field percent_settled", values[i])
			} else if value != nil {
				_m.PercentSettled = *value
			}
		case paymentorder.FieldSenderFee:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field sender_fee", values[i])
			} else if value != nil {
				_m.SenderFee = *value
			}
		case paymentorder.FieldNetworkFee:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field network_fee", values[i])
			} else if value != nil {
				_m.NetworkFee = *value
			}
		case paymentorder.FieldRate:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value != nil {
				_m.Rate = *value
			}
		case paymentorder.FieldTxHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tx_hash", values[i])
			} else if value.Valid {
				_m.TxHash = value.String
			}
		case paymentorder.FieldBlockNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field block_number", values[i])
			} else if value.Valid {
				_m.BlockNumber = value.Int64
			}
		case paymentorder.FieldFromAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_address", values[i])
			} else if value.Valid {
				_m.FromAddress = value.String
			}
		case paymentorder.FieldReturnAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field return_address", values[i])
			} else if value.Valid {
				_m.ReturnAddress = value.String
			}
		case paymentorder.FieldReceiveAddressText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field receive_address_text", values[i])
			} else if value.Valid {
				_m.ReceiveAddressText = value.String
			}
		case paymentorder.FieldFeePercent:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field fee_percent", values[i])
			} else if value != nil {
				_m.FeePercent = *value
			}
		case paymentorder.FieldFeeAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fee_address", values[i])
			} else if value.Valid {
				_m.FeeAddress = value.String
			}
		case paymentorder.FieldGatewayID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_id", values[i])
			} else if value.Valid {
				_m.GatewayID = value.String
			}
		case paymentorder.FieldMessageHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_hash", values[i])
			} else if value.Valid {
				_m.MessageHash = value.String
			}
		case paymentorder.FieldReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference", values[i])
			} else if value.Valid {
				_m.Reference = value.String
			}
		case paymentorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = paymentorder.Status(value.String)
			}
		case paymentorder.FieldAmountInUsd:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount_in_usd", values[i])
			} else if value != nil {
				_m.AmountInUsd = *value
			}
		case paymentorder.FieldOrderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_type", values[i])
			} else if value.Valid {
				_m.OrderType = paymentorder.OrderType(value.String)
			}
		case paymentorder.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_payment_orders", values[i])
			} else if value.Valid {
				_m.api_key_payment_orders = new(uuid.UUID)
				*_m.api_key_payment_orders = *value.S.(*uuid.UUID)
			}
		case paymentorder.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field linked_address_payment_orders", value)
			} else if value.Valid {
				_m.linked_address_payment_orders = new(int)
				*_m.linked_address_payment_orders = int(value.Int64)
			}
		case paymentorder.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field sender_profile_payment_orders", values[i])
			} else if value.Valid {
				_m.sender_profile_payment_orders = new(uuid.UUID)
				*_m.sender_profile_payment_orders = *value.S.(*uuid.UUID)
			}
		case paymentorder.ForeignKeys[3]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field token_payment_orders", value)
			} else if value.Valid {
				_m.token_payment_orders = new(int)
				*_m.token_payment_orders = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentOrder.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySenderProfile queries the "sender_profile" edge of the PaymentOrder entity.
func (_m *PaymentOrder) QuerySenderProfile() *SenderProfileQuery {
	return NewPaymentOrderClient(_m.config).QuerySenderProfile(_m)
}

// QueryToken queries the "token" edge of the PaymentOrder entity.
func (_m *PaymentOrder) QueryToken() *TokenQuery {
	return NewPaymentOrderClient(_m.config).QueryToken(_m)
}

// QueryLinkedAddress queries the "linked_address" edge of the PaymentOrder entity.
func (_m *PaymentOrder) QueryLinkedAddress() *LinkedAddressQuery {
	return NewPaymentOrderClient(_m.config).QueryLinkedAddress(_m)
}

// QueryReceiveAddress queries the "receive_address" edge of the PaymentOrder entity.
func (_m *PaymentOrder) QueryReceiveAddress() *ReceiveAddressQuery {
	return NewPaymentOrderClient(_m.config).QueryReceiveAddress(_m)
}

// QueryRecipient queries the "recipient" edge of the PaymentOrder entity.
func (_m *PaymentOrder) QueryRecipient() *PaymentOrderRecipientQuery {
	return NewPaymentOrderClient(_m.config).QueryRecipient(_m)
}

// QueryTransactions queries the "transactions" edge of the PaymentOrder entity.
func (_m *PaymentOrder) QueryTransactions() *TransactionLogQuery {
	return NewPaymentOrderClient(_m.config).QueryTransactions(_m)
}

// QueryPaymentWebhook queries the "payment_webhook" edge of the PaymentOrder entity.
func (_m *PaymentOrder) QueryPaymentWebhook() *PaymentWebhookQuery {
	return NewPaymentOrderClient(_m.config).QueryPaymentWebhook(_m)
}

// Update returns a builder for updating this PaymentOrder.
// Note that you need to call PaymentOrder.Unwrap() before calling this method if this PaymentOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentOrder) Update() *PaymentOrderUpdateOne {
	return NewPaymentOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentOrder) Unwrap() *PaymentOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentOrder) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("amount_paid=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountPaid))
	builder.WriteString(", ")
	builder.WriteString("amount_returned=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountReturned))
	builder.WriteString(", ")
	builder.WriteString("percent_settled=")
	builder.WriteString(fmt.Sprintf("%v", _m.PercentSettled))
	builder.WriteString(", ")
	builder.WriteString("sender_fee=")
	builder.WriteString(fmt.Sprintf("%v", _m.SenderFee))
	builder.WriteString(", ")
	builder.WriteString("network_fee=")
	builder.WriteString(fmt.Sprintf("%v", _m.NetworkFee))
	builder.WriteString(", ")
	builder.WriteString("rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rate))
	builder.WriteString(", ")
	builder.WriteString("tx_hash=")
	builder.WriteString(_m.TxHash)
	builder.WriteString(", ")
	builder.WriteString("block_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.BlockNumber))
	builder.WriteString(", ")
	builder.WriteString("from_address=")
	builder.WriteString(_m.FromAddress)
	builder.WriteString(", ")
	builder.WriteString("return_address=")
	builder.WriteString(_m.ReturnAddress)
	builder.WriteString(", ")
	builder.WriteString("receive_address_text=")
	builder.WriteString(_m.ReceiveAddressText)
	builder.WriteString(", ")
	builder.WriteString("fee_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeePercent))
	builder.WriteString(", ")
	builder.WriteString("fee_address=")
	builder.WriteString(_m.FeeAddress)
	builder.WriteString(", ")
	builder.WriteString("gateway_id=")
	builder.WriteString(_m.GatewayID)
	builder.WriteString(", ")
	builder.WriteString("message_hash=")
	builder.WriteString(_m.MessageHash)
	builder.WriteString(", ")
	builder.WriteString("reference=")
	builder.WriteString(_m.Reference)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("amount_in_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountInUsd))
	builder.WriteString(", ")
	builder.WriteString("order_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderType))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentOrders is a parsable slice of PaymentOrder.
type PaymentOrders []*PaymentOrder
