// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/paycrest/aggregator/ent/paymentorder"
	"github.com/paycrest/aggregator/ent/paymentorderrecipient"
	"github.com/paycrest/aggregator/ent/predicate"
)

// PaymentOrderRecipientUpdate is the builder for updating PaymentOrderRecipient entities.
type PaymentOrderRecipientUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentOrderRecipientMutation
}

// Where appends a list predicates to the PaymentOrderRecipientUpdate builder.
func (_u *PaymentOrderRecipientUpdate) Where(ps ...predicate.PaymentOrderRecipient) *PaymentOrderRecipientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInstitution sets the "institution" field.
func (_u *PaymentOrderRecipientUpdate) SetInstitution(v string) *PaymentOrderRecipientUpdate {
	_u.mutation.SetInstitution(v)
	return _u
}

// SetNillableInstitution sets the "institution" field if the given value is not nil.
func (_u *PaymentOrderRecipientUpdate) SetNillableInstitution(v *string) *PaymentOrderRecipientUpdate {
	if v != nil {
		_u.SetInstitution(*v)
	}
	return _u
}

// SetAccountIdentifier sets the "account_identifier" field.
func (_u *PaymentOrderRecipientUpdate) SetAccountIdentifier(v string) *PaymentOrderRecipientUpdate {
	_u.mutation.SetAccountIdentifier(v)
	return _u
}

// SetNillableAccountIdentifier sets the "account_identifier" field if the given value is not nil.
func (_u *PaymentOrderRecipientUpdate) SetNillableAccountIdentifier(v *string) *PaymentOrderRecipientUpdate {
	if v != nil {
		_u.SetAccountIdentifier(*v)
	}
	return _u
}

// SetAccountName sets the "account_name" field.
func (_u *PaymentOrderRecipientUpdate) SetAccountName(v string) *PaymentOrderRecipientUpdate {
	_u.mutation.SetAccountName(v)
	return _u
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_u *PaymentOrderRecipientUpdate) SetNillableAccountName(v *string) *PaymentOrderRecipientUpdate {
	if v != nil {
		_u.SetAccountName(*v)
	}
	return _u
}

// SetMemo sets the "memo" field.
func (_u *PaymentOrderRecipientUpdate) SetMemo(v string) *PaymentOrderRecipientUpdate {
	_u.mutation.SetMemo(v)
	return _u
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_u *PaymentOrderRecipientUpdate) SetNillableMemo(v *string) *PaymentOrderRecipientUpdate {
	if v != nil {
		_u.SetMemo(*v)
	}
	return _u
}

// ClearMemo clears the value of the "memo" field.
func (_u *PaymentOrderRecipientUpdate) ClearMemo() *PaymentOrderRecipientUpdate {
	_u.mutation.ClearMemo()
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *PaymentOrderRecipientUpdate) SetProviderID(v string) *PaymentOrderRecipientUpdate {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *PaymentOrderRecipientUpdate) SetNillableProviderID(v *string) *PaymentOrderRecipientUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// ClearProviderID clears the value of the "provider_id" field.
func (_u *PaymentOrderRecipientUpdate) ClearProviderID() *PaymentOrderRecipientUpdate {
	_u.mutation.ClearProviderID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PaymentOrderRecipientUpdate) SetMetadata(v map[string]interface{}) *PaymentOrderRecipientUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *PaymentOrderRecipientUpdate) ClearMetadata() *PaymentOrderRecipientUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetPaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID.
func (_u *PaymentOrderRecipientUpdate) SetPaymentOrderID(id uuid.UUID) *PaymentOrderRecipientUpdate {
	_u.mutation.SetPaymentOrderID(id)
	return _u
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (_u *PaymentOrderRecipientUpdate) SetPaymentOrder(v *PaymentOrder) *PaymentOrderRecipientUpdate {
	return _u.SetPaymentOrderID(v.ID)
}

// Mutation returns the PaymentOrderRecipientMutation object of the builder.
func (_u *PaymentOrderRecipientUpdate) Mutation() *PaymentOrderRecipientMutation {
	return _u.mutation
}

// ClearPaymentOrder clears the "payment_order" edge to the PaymentOrder entity.
func (_u *PaymentOrderRecipientUpdate) ClearPaymentOrder() *PaymentOrderRecipientUpdate {
	_u.mutation.ClearPaymentOrder()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentOrderRecipientUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderRecipientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentOrderRecipientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderRecipientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderRecipientUpdate) check() error {
	if _u.mutation.PaymentOrderCleared() && len(_u.mutation.PaymentOrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrderRecipient.payment_order"`)
	}
	return nil
}

func (_u *PaymentOrderRecipientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorderrecipient.Table, paymentorderrecipient.Columns, sqlgraph.NewFieldSpec(paymentorderrecipient.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Institution(); ok {
		_spec.SetField(paymentorderrecipient.FieldInstitution, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountIdentifier(); ok {
		_spec.SetField(paymentorderrecipient.FieldAccountIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountName(); ok {
		_spec.SetField(paymentorderrecipient.FieldAccountName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Memo(); ok {
		_spec.SetField(paymentorderrecipient.FieldMemo, field.TypeString, value)
	}
	if _u.mutation.MemoCleared() {
		_spec.ClearField(paymentorderrecipient.FieldMemo, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(paymentorderrecipient.FieldProviderID, field.TypeString, value)
	}
	if _u.mutation.ProviderIDCleared() {
		_spec.ClearField(paymentorderrecipient.FieldProviderID, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(paymentorderrecipient.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(paymentorderrecipient.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.PaymentOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentorderrecipient.PaymentOrderTable,
			Columns: []string{paymentorderrecipient.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentorderrecipient.PaymentOrderTable,
			Columns: []string{paymentorderrecipient.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorderrecipient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentOrderRecipientUpdateOne is the builder for updating a single PaymentOrderRecipient entity.
type PaymentOrderRecipientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentOrderRecipientMutation
}

// SetInstitution sets the "institution" field.
func (_u *PaymentOrderRecipientUpdateOne) SetInstitution(v string) *PaymentOrderRecipientUpdateOne {
	_u.mutation.SetInstitution(v)
	return _u
}

// SetNillableInstitution sets the "institution" field if the given value is not nil.
func (_u *PaymentOrderRecipientUpdateOne) SetNillableInstitution(v *string) *PaymentOrderRecipientUpdateOne {
	if v != nil {
		_u.SetInstitution(*v)
	}
	return _u
}

// SetAccountIdentifier sets the "account_identifier" field.
func (_u *PaymentOrderRecipientUpdateOne) SetAccountIdentifier(v string) *PaymentOrderRecipientUpdateOne {
	_u.mutation.SetAccountIdentifier(v)
	return _u
}

// SetNillableAccountIdentifier sets the "account_identifier" field if the given value is not nil.
func (_u *PaymentOrderRecipientUpdateOne) SetNillableAccountIdentifier(v *string) *PaymentOrderRecipientUpdateOne {
	if v != nil {
		_u.SetAccountIdentifier(*v)
	}
	return _u
}

// SetAccountName sets the "account_name" field.
func (_u *PaymentOrderRecipientUpdateOne) SetAccountName(v string) *PaymentOrderRecipientUpdateOne {
	_u.mutation.SetAccountName(v)
	return _u
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_u *PaymentOrderRecipientUpdateOne) SetNillableAccountName(v *string) *PaymentOrderRecipientUpdateOne {
	if v != nil {
		_u.SetAccountName(*v)
	}
	return _u
}

// SetMemo sets the "memo" field.
func (_u *PaymentOrderRecipientUpdateOne) SetMemo(v string) *PaymentOrderRecipientUpdateOne {
	_u.mutation.SetMemo(v)
	return _u
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_u *PaymentOrderRecipientUpdateOne) SetNillableMemo(v *string) *PaymentOrderRecipientUpdateOne {
	if v != nil {
		_u.SetMemo(*v)
	}
	return _u
}

// ClearMemo clears the value of the "memo" field.
func (_u *PaymentOrderRecipientUpdateOne) ClearMemo() *PaymentOrderRecipientUpdateOne {
	_u.mutation.ClearMemo()
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *PaymentOrderRecipientUpdateOne) SetProviderID(v string) *PaymentOrderRecipientUpdateOne {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *PaymentOrderRecipientUpdateOne) SetNillableProviderID(v *string) *PaymentOrderRecipientUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// ClearProviderID clears the value of the "provider_id" field.
func (_u *PaymentOrderRecipientUpdateOne) ClearProviderID() *PaymentOrderRecipientUpdateOne {
	_u.mutation.ClearProviderID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PaymentOrderRecipientUpdateOne) SetMetadata(v map[string]interface{}) *PaymentOrderRecipientUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *PaymentOrderRecipientUpdateOne) ClearMetadata() *PaymentOrderRecipientUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetPaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID.
func (_u *PaymentOrderRecipientUpdateOne) SetPaymentOrderID(id uuid.UUID) *PaymentOrderRecipientUpdateOne {
	_u.mutation.SetPaymentOrderID(id)
	return _u
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (_u *PaymentOrderRecipientUpdateOne) SetPaymentOrder(v *PaymentOrder) *PaymentOrderRecipientUpdateOne {
	return _u.SetPaymentOrderID(v.ID)
}

// Mutation returns the PaymentOrderRecipientMutation object of the builder.
func (_u *PaymentOrderRecipientUpdateOne) Mutation() *PaymentOrderRecipientMutation {
	return _u.mutation
}

// ClearPaymentOrder clears the "payment_order" edge to the PaymentOrder entity.
func (_u *PaymentOrderRecipientUpdateOne) ClearPaymentOrder() *PaymentOrderRecipientUpdateOne {
	_u.mutation.ClearPaymentOrder()
	return _u
}

// Where appends a list predicates to the PaymentOrderRecipientUpdate builder.
func (_u *PaymentOrderRecipientUpdateOne) Where(ps ...predicate.PaymentOrderRecipient) *PaymentOrderRecipientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentOrderRecipientUpdateOne) Select(field string, fields ...string) *PaymentOrderRecipientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentOrderRecipient entity.
func (_u *PaymentOrderRecipientUpdateOne) Save(ctx context.Context) (*PaymentOrderRecipient, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderRecipientUpdateOne) SaveX(ctx context.Context) *PaymentOrderRecipient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentOrderRecipientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderRecipientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderRecipientUpdateOne) check() error {
	if _u.mutation.PaymentOrderCleared() && len(_u.mutation.PaymentOrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrderRecipient.payment_order"`)
	}
	return nil
}

func (_u *PaymentOrderRecipientUpdateOne) sqlSave(ctx context.Context) (_node *PaymentOrderRecipient, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorderrecipient.Table, paymentorderrecipient.Columns, sqlgraph.NewFieldSpec(paymentorderrecipient.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentOrderRecipient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentorderrecipient.FieldID)
		for _, f := range fields {
			if !paymentorderrecipient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentorderrecipient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Institution(); ok {
		_spec.SetField(paymentorderrecipient.FieldInstitution, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountIdentifier(); ok {
		_spec.SetField(paymentorderrecipient.FieldAccountIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountName(); ok {
		_spec.SetField(paymentorderrecipient.FieldAccountName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Memo(); ok {
		_spec.SetField(paymentorderrecipient.FieldMemo, field.TypeString, value)
	}
	if _u.mutation.MemoCleared() {
		_spec.ClearField(paymentorderrecipient.FieldMemo, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(paymentorderrecipient.FieldProviderID, field.TypeString, value)
	}
	if _u.mutation.ProviderIDCleared() {
		_spec.ClearField(paymentorderrecipient.FieldProviderID, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(paymentorderrecipient.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(paymentorderrecipient.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.PaymentOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentorderrecipient.PaymentOrderTable,
			Columns: []string{paymentorderrecipient.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentorderrecipient.PaymentOrderTable,
			Columns: []string{paymentorderrecipient.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentOrderRecipient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorderrecipient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
