// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/paycrest/aggregator/ent/paymentorder"
	"github.com/paycrest/aggregator/ent/providerassignmentrun"
	"github.com/paycrest/aggregator/ent/providerordertoken"
	"github.com/shopspring/decimal"
)

// ProviderAssignmentRunCreate is the builder for creating a ProviderAssignmentRun entity.
type ProviderAssignmentRunCreate struct {
	config
	mutation *ProviderAssignmentRunMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAssignedProviderID sets the "assigned_provider_id" field.
func (_c *ProviderAssignmentRunCreate) SetAssignedProviderID(v string) *ProviderAssignmentRunCreate {
	_c.mutation.SetAssignedProviderID(v)
	return _c
}

// SetNillableAssignedProviderID sets the "assigned_provider_id" field if the given value is not nil.
func (_c *ProviderAssignmentRunCreate) SetNillableAssignedProviderID(v *string) *ProviderAssignmentRunCreate {
	if v != nil {
		_c.SetAssignedProviderID(*v)
	}
	return _c
}

// SetAttemptedAt sets the "attempted_at" field.
func (_c *ProviderAssignmentRunCreate) SetAttemptedAt(v time.Time) *ProviderAssignmentRunCreate {
	_c.mutation.SetAttemptedAt(v)
	return _c
}

// SetNillableAttemptedAt sets the "attempted_at" field if the given value is not nil.
func (_c *ProviderAssignmentRunCreate) SetNillableAttemptedAt(v *time.Time) *ProviderAssignmentRunCreate {
	if v != nil {
		_c.SetAttemptedAt(*v)
	}
	return _c
}

// SetTrigger sets the "trigger" field.
func (_c *ProviderAssignmentRunCreate) SetTrigger(v string) *ProviderAssignmentRunCreate {
	_c.mutation.SetTrigger(v)
	return _c
}

// SetResult sets the "result" field.
func (_c *ProviderAssignmentRunCreate) SetResult(v string) *ProviderAssignmentRunCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetUsedFallback sets the "used_fallback" field.
func (_c *ProviderAssignmentRunCreate) SetUsedFallback(v bool) *ProviderAssignmentRunCreate {
	_c.mutation.SetUsedFallback(v)
	return _c
}

// SetNillableUsedFallback sets the "used_fallback" field if the given value is not nil.
func (_c *ProviderAssignmentRunCreate) SetNillableUsedFallback(v *bool) *ProviderAssignmentRunCreate {
	if v != nil {
		_c.SetUsedFallback(*v)
	}
	return _c
}

// SetMarketBuyRateSnapshot sets the "market_buy_rate_snapshot" field.
func (_c *ProviderAssignmentRunCreate) SetMarketBuyRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunCreate {
	_c.mutation.SetMarketBuyRateSnapshot(v)
	return _c
}

// SetNillableMarketBuyRateSnapshot sets the "market_buy_rate_snapshot" field if the given value is not nil.
func (_c *ProviderAssignmentRunCreate) SetNillableMarketBuyRateSnapshot(v *decimal.Decimal) *ProviderAssignmentRunCreate {
	if v != nil {
		_c.SetMarketBuyRateSnapshot(*v)
	}
	return _c
}

// SetMarketSellRateSnapshot sets the "market_sell_rate_snapshot" field.
func (_c *ProviderAssignmentRunCreate) SetMarketSellRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunCreate {
	_c.mutation.SetMarketSellRateSnapshot(v)
	return _c
}

// SetNillableMarketSellRateSnapshot sets the "market_sell_rate_snapshot" field if the given value is not nil.
func (_c *ProviderAssignmentRunCreate) SetNillableMarketSellRateSnapshot(v *decimal.Decimal) *ProviderAssignmentRunCreate {
	if v != nil {
		_c.SetMarketSellRateSnapshot(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *ProviderAssignmentRunCreate) SetErrorMessage(v string) *ProviderAssignmentRunCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *ProviderAssignmentRunCreate) SetNillableErrorMessage(v *string) *ProviderAssignmentRunCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProviderAssignmentRunCreate) SetID(v uuid.UUID) *ProviderAssignmentRunCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProviderAssignmentRunCreate) SetNillableID(v *uuid.UUID) *ProviderAssignmentRunCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID.
func (_c *ProviderAssignmentRunCreate) SetPaymentOrderID(id uuid.UUID) *ProviderAssignmentRunCreate {
	_c.mutation.SetPaymentOrderID(id)
	return _c
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (_c *ProviderAssignmentRunCreate) SetPaymentOrder(v *PaymentOrder) *ProviderAssignmentRunCreate {
	return _c.SetPaymentOrderID(v.ID)
}

// SetProviderOrderTokenID sets the "provider_order_token" edge to the ProviderOrderToken entity by ID.
func (_c *ProviderAssignmentRunCreate) SetProviderOrderTokenID(id int) *ProviderAssignmentRunCreate {
	_c.mutation.SetProviderOrderTokenID(id)
	return _c
}

// SetNillableProviderOrderTokenID sets the "provider_order_token" edge to the ProviderOrderToken entity by ID if the given value is not nil.
func (_c *ProviderAssignmentRunCreate) SetNillableProviderOrderTokenID(id *int) *ProviderAssignmentRunCreate {
	if id != nil {
		_c = _c.SetProviderOrderTokenID(*id)
	}
	return _c
}

// SetProviderOrderToken sets the "provider_order_token" edge to the ProviderOrderToken entity.
func (_c *ProviderAssignmentRunCreate) SetProviderOrderToken(v *ProviderOrderToken) *ProviderAssignmentRunCreate {
	return _c.SetProviderOrderTokenID(v.ID)
}

// Mutation returns the ProviderAssignmentRunMutation object of the builder.
func (_c *ProviderAssignmentRunCreate) Mutation() *ProviderAssignmentRunMutation {
	return _c.mutation
}

// Save creates the ProviderAssignmentRun in the database.
func (_c *ProviderAssignmentRunCreate) Save(ctx context.Context) (*ProviderAssignmentRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProviderAssignmentRunCreate) SaveX(ctx context.Context) *ProviderAssignmentRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderAssignmentRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderAssignmentRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProviderAssignmentRunCreate) defaults() {
	if _, ok := _c.mutation.AttemptedAt(); !ok {
		v := providerassignmentrun.DefaultAttemptedAt()
		_c.mutation.SetAttemptedAt(v)
	}
	if _, ok := _c.mutation.UsedFallback(); !ok {
		v := providerassignmentrun.DefaultUsedFallback
		_c.mutation.SetUsedFallback(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := providerassignmentrun.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProviderAssignmentRunCreate) check() error {
	if v, ok := _c.mutation.AssignedProviderID(); ok {
		if err := providerassignmentrun.AssignedProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "assigned_provider_id", err: fmt.Errorf(`ent: validator failed for field "ProviderAssignmentRun.assigned_provider_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AttemptedAt(); !ok {
		return &ValidationError{Name: "attempted_at", err: errors.New(`ent: missing required field "ProviderAssignmentRun.attempted_at"`)}
	}
	if _, ok := _c.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "ProviderAssignmentRun.trigger"`)}
	}
	if v, ok := _c.mutation.Trigger(); ok {
		if err := providerassignmentrun.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "ProviderAssignmentRun.trigger": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "ProviderAssignmentRun.result"`)}
	}
	if v, ok := _c.mutation.Result(); ok {
		if err := providerassignmentrun.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "ProviderAssignmentRun.result": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UsedFallback(); !ok {
		return &ValidationError{Name: "used_fallback", err: errors.New(`ent: missing required field "ProviderAssignmentRun.used_fallback"`)}
	}
	if len(_c.mutation.PaymentOrderIDs()) == 0 {
		return &ValidationError{Name: "payment_order", err: errors.New(`ent: missing required edge "ProviderAssignmentRun.payment_order"`)}
	}
	return nil
}

func (_c *ProviderAssignmentRunCreate) sqlSave(ctx context.Context) (*ProviderAssignmentRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProviderAssignmentRunCreate) createSpec() (*ProviderAssignmentRun, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderAssignmentRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(providerassignmentrun.Table, sqlgraph.NewFieldSpec(providerassignmentrun.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.AssignedProviderID(); ok {
		_spec.SetField(providerassignmentrun.FieldAssignedProviderID, field.TypeString, value)
		_node.AssignedProviderID = &value
	}
	if value, ok := _c.mutation.AttemptedAt(); ok {
		_spec.SetField(providerassignmentrun.FieldAttemptedAt, field.TypeTime, value)
		_node.AttemptedAt = value
	}
	if value, ok := _c.mutation.Trigger(); ok {
		_spec.SetField(providerassignmentrun.FieldTrigger, field.TypeString, value)
		_node.Trigger = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(providerassignmentrun.FieldResult, field.TypeString, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.UsedFallback(); ok {
		_spec.SetField(providerassignmentrun.FieldUsedFallback, field.TypeBool, value)
		_node.UsedFallback = value
	}
	if value, ok := _c.mutation.MarketBuyRateSnapshot(); ok {
		_spec.SetField(providerassignmentrun.FieldMarketBuyRateSnapshot, field.TypeFloat64, value)
		_node.MarketBuyRateSnapshot = &value
	}
	if value, ok := _c.mutation.MarketSellRateSnapshot(); ok {
		_spec.SetField(providerassignmentrun.FieldMarketSellRateSnapshot, field.TypeFloat64, value)
		_node.MarketSellRateSnapshot = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(providerassignmentrun.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if nodes := _c.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerassignmentrun.PaymentOrderTable,
			Columns: []string{providerassignmentrun.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.payment_order_provider_assignment_runs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProviderOrderTokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerassignmentrun.ProviderOrderTokenTable,
			Columns: []string{providerassignmentrun.ProviderOrderTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerordertoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.provider_order_token_assignment_runs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderAssignmentRun.Create().
//		SetAssignedProviderID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderAssignmentRunUpsert) {
//			SetAssignedProviderID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderAssignmentRunCreate) OnConflict(opts ...sql.ConflictOption) *ProviderAssignmentRunUpsertOne {
	_c.conflict = opts
	return &ProviderAssignmentRunUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderAssignmentRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderAssignmentRunCreate) OnConflictColumns(columns ...string) *ProviderAssignmentRunUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderAssignmentRunUpsertOne{
		create: _c,
	}
}

type (
	// ProviderAssignmentRunUpsertOne is the builder for "upsert"-ing
	//  one ProviderAssignmentRun node.
	ProviderAssignmentRunUpsertOne struct {
		create *ProviderAssignmentRunCreate
	}

	// ProviderAssignmentRunUpsert is the "OnConflict" setter.
	ProviderAssignmentRunUpsert struct {
		*sql.UpdateSet
	}
)

// SetAssignedProviderID sets the "assigned_provider_id" field.
func (u *ProviderAssignmentRunUpsert) SetAssignedProviderID(v string) *ProviderAssignmentRunUpsert {
	u.Set(providerassignmentrun.FieldAssignedProviderID, v)
	return u
}

// UpdateAssignedProviderID sets the "assigned_provider_id" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsert) UpdateAssignedProviderID() *ProviderAssignmentRunUpsert {
	u.SetExcluded(providerassignmentrun.FieldAssignedProviderID)
	return u
}

// ClearAssignedProviderID clears the value of the "assigned_provider_id" field.
func (u *ProviderAssignmentRunUpsert) ClearAssignedProviderID() *ProviderAssignmentRunUpsert {
	u.SetNull(providerassignmentrun.FieldAssignedProviderID)
	return u
}

// SetAttemptedAt sets the "attempted_at" field.
func (u *ProviderAssignmentRunUpsert) SetAttemptedAt(v time.Time) *ProviderAssignmentRunUpsert {
	u.Set(providerassignmentrun.FieldAttemptedAt, v)
	return u
}

// UpdateAttemptedAt sets the "attempted_at" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsert) UpdateAttemptedAt() *ProviderAssignmentRunUpsert {
	u.SetExcluded(providerassignmentrun.FieldAttemptedAt)
	return u
}

// SetTrigger sets the "trigger" field.
func (u *ProviderAssignmentRunUpsert) SetTrigger(v string) *ProviderAssignmentRunUpsert {
	u.Set(providerassignmentrun.FieldTrigger, v)
	return u
}

// UpdateTrigger sets the "trigger" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsert) UpdateTrigger() *ProviderAssignmentRunUpsert {
	u.SetExcluded(providerassignmentrun.FieldTrigger)
	return u
}

// SetResult sets the "result" field.
func (u *ProviderAssignmentRunUpsert) SetResult(v string) *ProviderAssignmentRunUpsert {
	u.Set(providerassignmentrun.FieldResult, v)
	return u
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsert) UpdateResult() *ProviderAssignmentRunUpsert {
	u.SetExcluded(providerassignmentrun.FieldResult)
	return u
}

// SetUsedFallback sets the "used_fallback" field.
func (u *ProviderAssignmentRunUpsert) SetUsedFallback(v bool) *ProviderAssignmentRunUpsert {
	u.Set(providerassignmentrun.FieldUsedFallback, v)
	return u
}

// UpdateUsedFallback sets the "used_fallback" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsert) UpdateUsedFallback() *ProviderAssignmentRunUpsert {
	u.SetExcluded(providerassignmentrun.FieldUsedFallback)
	return u
}

// SetMarketBuyRateSnapshot sets the "market_buy_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsert) SetMarketBuyRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpsert {
	u.Set(providerassignmentrun.FieldMarketBuyRateSnapshot, v)
	return u
}

// UpdateMarketBuyRateSnapshot sets the "market_buy_rate_snapshot" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsert) UpdateMarketBuyRateSnapshot() *ProviderAssignmentRunUpsert {
	u.SetExcluded(providerassignmentrun.FieldMarketBuyRateSnapshot)
	return u
}

// AddMarketBuyRateSnapshot adds v to the "market_buy_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsert) AddMarketBuyRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpsert {
	u.Add(providerassignmentrun.FieldMarketBuyRateSnapshot, v)
	return u
}

// ClearMarketBuyRateSnapshot clears the value of the "market_buy_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsert) ClearMarketBuyRateSnapshot() *ProviderAssignmentRunUpsert {
	u.SetNull(providerassignmentrun.FieldMarketBuyRateSnapshot)
	return u
}

// SetMarketSellRateSnapshot sets the "market_sell_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsert) SetMarketSellRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpsert {
	u.Set(providerassignmentrun.FieldMarketSellRateSnapshot, v)
	return u
}

// UpdateMarketSellRateSnapshot sets the "market_sell_rate_snapshot" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsert) UpdateMarketSellRateSnapshot() *ProviderAssignmentRunUpsert {
	u.SetExcluded(providerassignmentrun.FieldMarketSellRateSnapshot)
	return u
}

// AddMarketSellRateSnapshot adds v to the "market_sell_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsert) AddMarketSellRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpsert {
	u.Add(providerassignmentrun.FieldMarketSellRateSnapshot, v)
	return u
}

// ClearMarketSellRateSnapshot clears the value of the "market_sell_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsert) ClearMarketSellRateSnapshot() *ProviderAssignmentRunUpsert {
	u.SetNull(providerassignmentrun.FieldMarketSellRateSnapshot)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *ProviderAssignmentRunUpsert) SetErrorMessage(v string) *ProviderAssignmentRunUpsert {
	u.Set(providerassignmentrun.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsert) UpdateErrorMessage() *ProviderAssignmentRunUpsert {
	u.SetExcluded(providerassignmentrun.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ProviderAssignmentRunUpsert) ClearErrorMessage() *ProviderAssignmentRunUpsert {
	u.SetNull(providerassignmentrun.FieldErrorMessage)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ProviderAssignmentRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(providerassignmentrun.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProviderAssignmentRunUpsertOne) UpdateNewValues() *ProviderAssignmentRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(providerassignmentrun.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderAssignmentRun.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProviderAssignmentRunUpsertOne) Ignore() *ProviderAssignmentRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderAssignmentRunUpsertOne) DoNothing() *ProviderAssignmentRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderAssignmentRunCreate.OnConflict
// documentation for more info.
func (u *ProviderAssignmentRunUpsertOne) Update(set func(*ProviderAssignmentRunUpsert)) *ProviderAssignmentRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderAssignmentRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetAssignedProviderID sets the "assigned_provider_id" field.
func (u *ProviderAssignmentRunUpsertOne) SetAssignedProviderID(v string) *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetAssignedProviderID(v)
	})
}

// UpdateAssignedProviderID sets the "assigned_provider_id" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertOne) UpdateAssignedProviderID() *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateAssignedProviderID()
	})
}

// ClearAssignedProviderID clears the value of the "assigned_provider_id" field.
func (u *ProviderAssignmentRunUpsertOne) ClearAssignedProviderID() *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.ClearAssignedProviderID()
	})
}

// SetAttemptedAt sets the "attempted_at" field.
func (u *ProviderAssignmentRunUpsertOne) SetAttemptedAt(v time.Time) *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetAttemptedAt(v)
	})
}

// UpdateAttemptedAt sets the "attempted_at" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertOne) UpdateAttemptedAt() *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateAttemptedAt()
	})
}

// SetTrigger sets the "trigger" field.
func (u *ProviderAssignmentRunUpsertOne) SetTrigger(v string) *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetTrigger(v)
	})
}

// UpdateTrigger sets the "trigger" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertOne) UpdateTrigger() *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateTrigger()
	})
}

// SetResult sets the "result" field.
func (u *ProviderAssignmentRunUpsertOne) SetResult(v string) *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertOne) UpdateResult() *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateResult()
	})
}

// SetUsedFallback sets the "used_fallback" field.
func (u *ProviderAssignmentRunUpsertOne) SetUsedFallback(v bool) *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetUsedFallback(v)
	})
}

// UpdateUsedFallback sets the "used_fallback" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertOne) UpdateUsedFallback() *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateUsedFallback()
	})
}

// SetMarketBuyRateSnapshot sets the "market_buy_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsertOne) SetMarketBuyRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetMarketBuyRateSnapshot(v)
	})
}

// AddMarketBuyRateSnapshot adds v to the "market_buy_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsertOne) AddMarketBuyRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.AddMarketBuyRateSnapshot(v)
	})
}

// UpdateMarketBuyRateSnapshot sets the "market_buy_rate_snapshot" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertOne) UpdateMarketBuyRateSnapshot() *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateMarketBuyRateSnapshot()
	})
}

// ClearMarketBuyRateSnapshot clears the value of the "market_buy_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsertOne) ClearMarketBuyRateSnapshot() *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.ClearMarketBuyRateSnapshot()
	})
}

// SetMarketSellRateSnapshot sets the "market_sell_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsertOne) SetMarketSellRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetMarketSellRateSnapshot(v)
	})
}

// AddMarketSellRateSnapshot adds v to the "market_sell_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsertOne) AddMarketSellRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.AddMarketSellRateSnapshot(v)
	})
}

// UpdateMarketSellRateSnapshot sets the "market_sell_rate_snapshot" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertOne) UpdateMarketSellRateSnapshot() *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateMarketSellRateSnapshot()
	})
}

// ClearMarketSellRateSnapshot clears the value of the "market_sell_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsertOne) ClearMarketSellRateSnapshot() *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.ClearMarketSellRateSnapshot()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ProviderAssignmentRunUpsertOne) SetErrorMessage(v string) *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertOne) UpdateErrorMessage() *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ProviderAssignmentRunUpsertOne) ClearErrorMessage() *ProviderAssignmentRunUpsertOne {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.ClearErrorMessage()
	})
}

// Exec executes the query.
func (u *ProviderAssignmentRunUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderAssignmentRunCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderAssignmentRunUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProviderAssignmentRunUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ProviderAssignmentRunUpsertOne.ID is not supported by MySQL driver. Use ProviderAssignmentRunUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProviderAssignmentRunUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProviderAssignmentRunCreateBulk is the builder for creating many ProviderAssignmentRun entities in bulk.
type ProviderAssignmentRunCreateBulk struct {
	config
	err      error
	builders []*ProviderAssignmentRunCreate
	conflict []sql.ConflictOption
}

// Save creates the ProviderAssignmentRun entities in the database.
func (_c *ProviderAssignmentRunCreateBulk) Save(ctx context.Context) ([]*ProviderAssignmentRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProviderAssignmentRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderAssignmentRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProviderAssignmentRunCreateBulk) SaveX(ctx context.Context) []*ProviderAssignmentRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderAssignmentRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderAssignmentRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderAssignmentRun.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderAssignmentRunUpsert) {
//			SetAssignedProviderID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderAssignmentRunCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProviderAssignmentRunUpsertBulk {
	_c.conflict = opts
	return &ProviderAssignmentRunUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderAssignmentRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderAssignmentRunCreateBulk) OnConflictColumns(columns ...string) *ProviderAssignmentRunUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderAssignmentRunUpsertBulk{
		create: _c,
	}
}

// ProviderAssignmentRunUpsertBulk is the builder for "upsert"-ing
// a bulk of ProviderAssignmentRun nodes.
type ProviderAssignmentRunUpsertBulk struct {
	create *ProviderAssignmentRunCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProviderAssignmentRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(providerassignmentrun.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProviderAssignmentRunUpsertBulk) UpdateNewValues() *ProviderAssignmentRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(providerassignmentrun.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderAssignmentRun.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProviderAssignmentRunUpsertBulk) Ignore() *ProviderAssignmentRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderAssignmentRunUpsertBulk) DoNothing() *ProviderAssignmentRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderAssignmentRunCreateBulk.OnConflict
// documentation for more info.
func (u *ProviderAssignmentRunUpsertBulk) Update(set func(*ProviderAssignmentRunUpsert)) *ProviderAssignmentRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderAssignmentRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetAssignedProviderID sets the "assigned_provider_id" field.
func (u *ProviderAssignmentRunUpsertBulk) SetAssignedProviderID(v string) *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetAssignedProviderID(v)
	})
}

// UpdateAssignedProviderID sets the "assigned_provider_id" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertBulk) UpdateAssignedProviderID() *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateAssignedProviderID()
	})
}

// ClearAssignedProviderID clears the value of the "assigned_provider_id" field.
func (u *ProviderAssignmentRunUpsertBulk) ClearAssignedProviderID() *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.ClearAssignedProviderID()
	})
}

// SetAttemptedAt sets the "attempted_at" field.
func (u *ProviderAssignmentRunUpsertBulk) SetAttemptedAt(v time.Time) *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetAttemptedAt(v)
	})
}

// UpdateAttemptedAt sets the "attempted_at" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertBulk) UpdateAttemptedAt() *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateAttemptedAt()
	})
}

// SetTrigger sets the "trigger" field.
func (u *ProviderAssignmentRunUpsertBulk) SetTrigger(v string) *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetTrigger(v)
	})
}

// UpdateTrigger sets the "trigger" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertBulk) UpdateTrigger() *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateTrigger()
	})
}

// SetResult sets the "result" field.
func (u *ProviderAssignmentRunUpsertBulk) SetResult(v string) *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertBulk) UpdateResult() *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateResult()
	})
}

// SetUsedFallback sets the "used_fallback" field.
func (u *ProviderAssignmentRunUpsertBulk) SetUsedFallback(v bool) *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetUsedFallback(v)
	})
}

// UpdateUsedFallback sets the "used_fallback" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertBulk) UpdateUsedFallback() *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateUsedFallback()
	})
}

// SetMarketBuyRateSnapshot sets the "market_buy_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsertBulk) SetMarketBuyRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetMarketBuyRateSnapshot(v)
	})
}

// AddMarketBuyRateSnapshot adds v to the "market_buy_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsertBulk) AddMarketBuyRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.AddMarketBuyRateSnapshot(v)
	})
}

// UpdateMarketBuyRateSnapshot sets the "market_buy_rate_snapshot" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertBulk) UpdateMarketBuyRateSnapshot() *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateMarketBuyRateSnapshot()
	})
}

// ClearMarketBuyRateSnapshot clears the value of the "market_buy_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsertBulk) ClearMarketBuyRateSnapshot() *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.ClearMarketBuyRateSnapshot()
	})
}

// SetMarketSellRateSnapshot sets the "market_sell_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsertBulk) SetMarketSellRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetMarketSellRateSnapshot(v)
	})
}

// AddMarketSellRateSnapshot adds v to the "market_sell_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsertBulk) AddMarketSellRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.AddMarketSellRateSnapshot(v)
	})
}

// UpdateMarketSellRateSnapshot sets the "market_sell_rate_snapshot" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertBulk) UpdateMarketSellRateSnapshot() *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateMarketSellRateSnapshot()
	})
}

// ClearMarketSellRateSnapshot clears the value of the "market_sell_rate_snapshot" field.
func (u *ProviderAssignmentRunUpsertBulk) ClearMarketSellRateSnapshot() *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.ClearMarketSellRateSnapshot()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ProviderAssignmentRunUpsertBulk) SetErrorMessage(v string) *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ProviderAssignmentRunUpsertBulk) UpdateErrorMessage() *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ProviderAssignmentRunUpsertBulk) ClearErrorMessage() *ProviderAssignmentRunUpsertBulk {
	return u.Update(func(s *ProviderAssignmentRunUpsert) {
		s.ClearErrorMessage()
	})
}

// Exec executes the query.
func (u *ProviderAssignmentRunUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProviderAssignmentRunCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderAssignmentRunCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderAssignmentRunUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
