// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/paycrest/aggregator/ent/paymentorder"
	"github.com/paycrest/aggregator/ent/predicate"
	"github.com/paycrest/aggregator/ent/providerassignmentrun"
	"github.com/paycrest/aggregator/ent/providerordertoken"
	"github.com/shopspring/decimal"
)

// ProviderAssignmentRunUpdate is the builder for updating ProviderAssignmentRun entities.
type ProviderAssignmentRunUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderAssignmentRunMutation
}

// Where appends a list predicates to the ProviderAssignmentRunUpdate builder.
func (_u *ProviderAssignmentRunUpdate) Where(ps ...predicate.ProviderAssignmentRun) *ProviderAssignmentRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAssignedProviderID sets the "assigned_provider_id" field.
func (_u *ProviderAssignmentRunUpdate) SetAssignedProviderID(v string) *ProviderAssignmentRunUpdate {
	_u.mutation.SetAssignedProviderID(v)
	return _u
}

// SetNillableAssignedProviderID sets the "assigned_provider_id" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdate) SetNillableAssignedProviderID(v *string) *ProviderAssignmentRunUpdate {
	if v != nil {
		_u.SetAssignedProviderID(*v)
	}
	return _u
}

// ClearAssignedProviderID clears the value of the "assigned_provider_id" field.
func (_u *ProviderAssignmentRunUpdate) ClearAssignedProviderID() *ProviderAssignmentRunUpdate {
	_u.mutation.ClearAssignedProviderID()
	return _u
}

// SetAttemptedAt sets the "attempted_at" field.
func (_u *ProviderAssignmentRunUpdate) SetAttemptedAt(v time.Time) *ProviderAssignmentRunUpdate {
	_u.mutation.SetAttemptedAt(v)
	return _u
}

// SetNillableAttemptedAt sets the "attempted_at" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdate) SetNillableAttemptedAt(v *time.Time) *ProviderAssignmentRunUpdate {
	if v != nil {
		_u.SetAttemptedAt(*v)
	}
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *ProviderAssignmentRunUpdate) SetTrigger(v string) *ProviderAssignmentRunUpdate {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdate) SetNillableTrigger(v *string) *ProviderAssignmentRunUpdate {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *ProviderAssignmentRunUpdate) SetResult(v string) *ProviderAssignmentRunUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdate) SetNillableResult(v *string) *ProviderAssignmentRunUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetUsedFallback sets the "used_fallback" field.
func (_u *ProviderAssignmentRunUpdate) SetUsedFallback(v bool) *ProviderAssignmentRunUpdate {
	_u.mutation.SetUsedFallback(v)
	return _u
}

// SetNillableUsedFallback sets the "used_fallback" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdate) SetNillableUsedFallback(v *bool) *ProviderAssignmentRunUpdate {
	if v != nil {
		_u.SetUsedFallback(*v)
	}
	return _u
}

// SetMarketBuyRateSnapshot sets the "market_buy_rate_snapshot" field.
func (_u *ProviderAssignmentRunUpdate) SetMarketBuyRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpdate {
	_u.mutation.ResetMarketBuyRateSnapshot()
	_u.mutation.SetMarketBuyRateSnapshot(v)
	return _u
}

// SetNillableMarketBuyRateSnapshot sets the "market_buy_rate_snapshot" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdate) SetNillableMarketBuyRateSnapshot(v *decimal.Decimal) *ProviderAssignmentRunUpdate {
	if v != nil {
		_u.SetMarketBuyRateSnapshot(*v)
	}
	return _u
}

// AddMarketBuyRateSnapshot adds value to the "market_buy_rate_snapshot" field.
func (_u *ProviderAssignmentRunUpdate) AddMarketBuyRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpdate {
	_u.mutation.AddMarketBuyRateSnapshot(v)
	return _u
}

// ClearMarketBuyRateSnapshot clears the value of the "market_buy_rate_snapshot" field.
func (_u *ProviderAssignmentRunUpdate) ClearMarketBuyRateSnapshot() *ProviderAssignmentRunUpdate {
	_u.mutation.ClearMarketBuyRateSnapshot()
	return _u
}

// SetMarketSellRateSnapshot sets the "market_sell_rate_snapshot" field.
func (_u *ProviderAssignmentRunUpdate) SetMarketSellRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpdate {
	_u.mutation.ResetMarketSellRateSnapshot()
	_u.mutation.SetMarketSellRateSnapshot(v)
	return _u
}

// SetNillableMarketSellRateSnapshot sets the "market_sell_rate_snapshot" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdate) SetNillableMarketSellRateSnapshot(v *decimal.Decimal) *ProviderAssignmentRunUpdate {
	if v != nil {
		_u.SetMarketSellRateSnapshot(*v)
	}
	return _u
}

// AddMarketSellRateSnapshot adds value to the "market_sell_rate_snapshot" field.
func (_u *ProviderAssignmentRunUpdate) AddMarketSellRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpdate {
	_u.mutation.AddMarketSellRateSnapshot(v)
	return _u
}

// ClearMarketSellRateSnapshot clears the value of the "market_sell_rate_snapshot" field.
func (_u *ProviderAssignmentRunUpdate) ClearMarketSellRateSnapshot() *ProviderAssignmentRunUpdate {
	_u.mutation.ClearMarketSellRateSnapshot()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ProviderAssignmentRunUpdate) SetErrorMessage(v string) *ProviderAssignmentRunUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdate) SetNillableErrorMessage(v *string) *ProviderAssignmentRunUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ProviderAssignmentRunUpdate) ClearErrorMessage() *ProviderAssignmentRunUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetPaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID.
func (_u *ProviderAssignmentRunUpdate) SetPaymentOrderID(id uuid.UUID) *ProviderAssignmentRunUpdate {
	_u.mutation.SetPaymentOrderID(id)
	return _u
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (_u *ProviderAssignmentRunUpdate) SetPaymentOrder(v *PaymentOrder) *ProviderAssignmentRunUpdate {
	return _u.SetPaymentOrderID(v.ID)
}

// SetProviderOrderTokenID sets the "provider_order_token" edge to the ProviderOrderToken entity by ID.
func (_u *ProviderAssignmentRunUpdate) SetProviderOrderTokenID(id int) *ProviderAssignmentRunUpdate {
	_u.mutation.SetProviderOrderTokenID(id)
	return _u
}

// SetNillableProviderOrderTokenID sets the "provider_order_token" edge to the ProviderOrderToken entity by ID if the given value is not nil.
func (_u *ProviderAssignmentRunUpdate) SetNillableProviderOrderTokenID(id *int) *ProviderAssignmentRunUpdate {
	if id != nil {
		_u = _u.SetProviderOrderTokenID(*id)
	}
	return _u
}

// SetProviderOrderToken sets the "provider_order_token" edge to the ProviderOrderToken entity.
func (_u *ProviderAssignmentRunUpdate) SetProviderOrderToken(v *ProviderOrderToken) *ProviderAssignmentRunUpdate {
	return _u.SetProviderOrderTokenID(v.ID)
}

// Mutation returns the ProviderAssignmentRunMutation object of the builder.
func (_u *ProviderAssignmentRunUpdate) Mutation() *ProviderAssignmentRunMutation {
	return _u.mutation
}

// ClearPaymentOrder clears the "payment_order" edge to the PaymentOrder entity.
func (_u *ProviderAssignmentRunUpdate) ClearPaymentOrder() *ProviderAssignmentRunUpdate {
	_u.mutation.ClearPaymentOrder()
	return _u
}

// ClearProviderOrderToken clears the "provider_order_token" edge to the ProviderOrderToken entity.
func (_u *ProviderAssignmentRunUpdate) ClearProviderOrderToken() *ProviderAssignmentRunUpdate {
	_u.mutation.ClearProviderOrderToken()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderAssignmentRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderAssignmentRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderAssignmentRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderAssignmentRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderAssignmentRunUpdate) check() error {
	if v, ok := _u.mutation.AssignedProviderID(); ok {
		if err := providerassignmentrun.AssignedProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "assigned_provider_id", err: fmt.Errorf(`ent: validator failed for field "ProviderAssignmentRun.assigned_provider_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Trigger(); ok {
		if err := providerassignmentrun.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "ProviderAssignmentRun.trigger": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := providerassignmentrun.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "ProviderAssignmentRun.result": %w`, err)}
		}
	}
	if _u.mutation.PaymentOrderCleared() && len(_u.mutation.PaymentOrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProviderAssignmentRun.payment_order"`)
	}
	return nil
}

func (_u *ProviderAssignmentRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerassignmentrun.Table, providerassignmentrun.Columns, sqlgraph.NewFieldSpec(providerassignmentrun.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AssignedProviderID(); ok {
		_spec.SetField(providerassignmentrun.FieldAssignedProviderID, field.TypeString, value)
	}
	if _u.mutation.AssignedProviderIDCleared() {
		_spec.ClearField(providerassignmentrun.FieldAssignedProviderID, field.TypeString)
	}
	if value, ok := _u.mutation.AttemptedAt(); ok {
		_spec.SetField(providerassignmentrun.FieldAttemptedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(providerassignmentrun.FieldTrigger, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(providerassignmentrun.FieldResult, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsedFallback(); ok {
		_spec.SetField(providerassignmentrun.FieldUsedFallback, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MarketBuyRateSnapshot(); ok {
		_spec.SetField(providerassignmentrun.FieldMarketBuyRateSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketBuyRateSnapshot(); ok {
		_spec.AddField(providerassignmentrun.FieldMarketBuyRateSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.MarketBuyRateSnapshotCleared() {
		_spec.ClearField(providerassignmentrun.FieldMarketBuyRateSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MarketSellRateSnapshot(); ok {
		_spec.SetField(providerassignmentrun.FieldMarketSellRateSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketSellRateSnapshot(); ok {
		_spec.AddField(providerassignmentrun.FieldMarketSellRateSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.MarketSellRateSnapshotCleared() {
		_spec.ClearField(providerassignmentrun.FieldMarketSellRateSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(providerassignmentrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(providerassignmentrun.FieldErrorMessage, field.TypeString)
	}
	if _u.mutation.PaymentOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerassignmentrun.PaymentOrderTable,
			Columns: []string{providerassignmentrun.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerassignmentrun.PaymentOrderTable,
			Columns: []string{providerassignmentrun.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProviderOrderTokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerassignmentrun.ProviderOrderTokenTable,
			Columns: []string{providerassignmentrun.ProviderOrderTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerordertoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderOrderTokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerassignmentrun.ProviderOrderTokenTable,
			Columns: []string{providerassignmentrun.ProviderOrderTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerordertoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerassignmentrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderAssignmentRunUpdateOne is the builder for updating a single ProviderAssignmentRun entity.
type ProviderAssignmentRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderAssignmentRunMutation
}

// SetAssignedProviderID sets the "assigned_provider_id" field.
func (_u *ProviderAssignmentRunUpdateOne) SetAssignedProviderID(v string) *ProviderAssignmentRunUpdateOne {
	_u.mutation.SetAssignedProviderID(v)
	return _u
}

// SetNillableAssignedProviderID sets the "assigned_provider_id" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdateOne) SetNillableAssignedProviderID(v *string) *ProviderAssignmentRunUpdateOne {
	if v != nil {
		_u.SetAssignedProviderID(*v)
	}
	return _u
}

// ClearAssignedProviderID clears the value of the "assigned_provider_id" field.
func (_u *ProviderAssignmentRunUpdateOne) ClearAssignedProviderID() *ProviderAssignmentRunUpdateOne {
	_u.mutation.ClearAssignedProviderID()
	return _u
}

// SetAttemptedAt sets the "attempted_at" field.
func (_u *ProviderAssignmentRunUpdateOne) SetAttemptedAt(v time.Time) *ProviderAssignmentRunUpdateOne {
	_u.mutation.SetAttemptedAt(v)
	return _u
}

// SetNillableAttemptedAt sets the "attempted_at" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdateOne) SetNillableAttemptedAt(v *time.Time) *ProviderAssignmentRunUpdateOne {
	if v != nil {
		_u.SetAttemptedAt(*v)
	}
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *ProviderAssignmentRunUpdateOne) SetTrigger(v string) *ProviderAssignmentRunUpdateOne {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdateOne) SetNillableTrigger(v *string) *ProviderAssignmentRunUpdateOne {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *ProviderAssignmentRunUpdateOne) SetResult(v string) *ProviderAssignmentRunUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdateOne) SetNillableResult(v *string) *ProviderAssignmentRunUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetUsedFallback sets the "used_fallback" field.
func (_u *ProviderAssignmentRunUpdateOne) SetUsedFallback(v bool) *ProviderAssignmentRunUpdateOne {
	_u.mutation.SetUsedFallback(v)
	return _u
}

// SetNillableUsedFallback sets the "used_fallback" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdateOne) SetNillableUsedFallback(v *bool) *ProviderAssignmentRunUpdateOne {
	if v != nil {
		_u.SetUsedFallback(*v)
	}
	return _u
}

// SetMarketBuyRateSnapshot sets the "market_buy_rate_snapshot" field.
func (_u *ProviderAssignmentRunUpdateOne) SetMarketBuyRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpdateOne {
	_u.mutation.ResetMarketBuyRateSnapshot()
	_u.mutation.SetMarketBuyRateSnapshot(v)
	return _u
}

// SetNillableMarketBuyRateSnapshot sets the "market_buy_rate_snapshot" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdateOne) SetNillableMarketBuyRateSnapshot(v *decimal.Decimal) *ProviderAssignmentRunUpdateOne {
	if v != nil {
		_u.SetMarketBuyRateSnapshot(*v)
	}
	return _u
}

// AddMarketBuyRateSnapshot adds value to the "market_buy_rate_snapshot" field.
func (_u *ProviderAssignmentRunUpdateOne) AddMarketBuyRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpdateOne {
	_u.mutation.AddMarketBuyRateSnapshot(v)
	return _u
}

// ClearMarketBuyRateSnapshot clears the value of the "market_buy_rate_snapshot" field.
func (_u *ProviderAssignmentRunUpdateOne) ClearMarketBuyRateSnapshot() *ProviderAssignmentRunUpdateOne {
	_u.mutation.ClearMarketBuyRateSnapshot()
	return _u
}

// SetMarketSellRateSnapshot sets the "market_sell_rate_snapshot" field.
func (_u *ProviderAssignmentRunUpdateOne) SetMarketSellRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpdateOne {
	_u.mutation.ResetMarketSellRateSnapshot()
	_u.mutation.SetMarketSellRateSnapshot(v)
	return _u
}

// SetNillableMarketSellRateSnapshot sets the "market_sell_rate_snapshot" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdateOne) SetNillableMarketSellRateSnapshot(v *decimal.Decimal) *ProviderAssignmentRunUpdateOne {
	if v != nil {
		_u.SetMarketSellRateSnapshot(*v)
	}
	return _u
}

// AddMarketSellRateSnapshot adds value to the "market_sell_rate_snapshot" field.
func (_u *ProviderAssignmentRunUpdateOne) AddMarketSellRateSnapshot(v decimal.Decimal) *ProviderAssignmentRunUpdateOne {
	_u.mutation.AddMarketSellRateSnapshot(v)
	return _u
}

// ClearMarketSellRateSnapshot clears the value of the "market_sell_rate_snapshot" field.
func (_u *ProviderAssignmentRunUpdateOne) ClearMarketSellRateSnapshot() *ProviderAssignmentRunUpdateOne {
	_u.mutation.ClearMarketSellRateSnapshot()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ProviderAssignmentRunUpdateOne) SetErrorMessage(v string) *ProviderAssignmentRunUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ProviderAssignmentRunUpdateOne) SetNillableErrorMessage(v *string) *ProviderAssignmentRunUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ProviderAssignmentRunUpdateOne) ClearErrorMessage() *ProviderAssignmentRunUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetPaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID.
func (_u *ProviderAssignmentRunUpdateOne) SetPaymentOrderID(id uuid.UUID) *ProviderAssignmentRunUpdateOne {
	_u.mutation.SetPaymentOrderID(id)
	return _u
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (_u *ProviderAssignmentRunUpdateOne) SetPaymentOrder(v *PaymentOrder) *ProviderAssignmentRunUpdateOne {
	return _u.SetPaymentOrderID(v.ID)
}

// SetProviderOrderTokenID sets the "provider_order_token" edge to the ProviderOrderToken entity by ID.
func (_u *ProviderAssignmentRunUpdateOne) SetProviderOrderTokenID(id int) *ProviderAssignmentRunUpdateOne {
	_u.mutation.SetProviderOrderTokenID(id)
	return _u
}

// SetNillableProviderOrderTokenID sets the "provider_order_token" edge to the ProviderOrderToken entity by ID if the given value is not nil.
func (_u *ProviderAssignmentRunUpdateOne) SetNillableProviderOrderTokenID(id *int) *ProviderAssignmentRunUpdateOne {
	if id != nil {
		_u = _u.SetProviderOrderTokenID(*id)
	}
	return _u
}

// SetProviderOrderToken sets the "provider_order_token" edge to the ProviderOrderToken entity.
func (_u *ProviderAssignmentRunUpdateOne) SetProviderOrderToken(v *ProviderOrderToken) *ProviderAssignmentRunUpdateOne {
	return _u.SetProviderOrderTokenID(v.ID)
}

// Mutation returns the ProviderAssignmentRunMutation object of the builder.
func (_u *ProviderAssignmentRunUpdateOne) Mutation() *ProviderAssignmentRunMutation {
	return _u.mutation
}

// ClearPaymentOrder clears the "payment_order" edge to the PaymentOrder entity.
func (_u *ProviderAssignmentRunUpdateOne) ClearPaymentOrder() *ProviderAssignmentRunUpdateOne {
	_u.mutation.ClearPaymentOrder()
	return _u
}

// ClearProviderOrderToken clears the "provider_order_token" edge to the ProviderOrderToken entity.
func (_u *ProviderAssignmentRunUpdateOne) ClearProviderOrderToken() *ProviderAssignmentRunUpdateOne {
	_u.mutation.ClearProviderOrderToken()
	return _u
}

// Where appends a list predicates to the ProviderAssignmentRunUpdate builder.
func (_u *ProviderAssignmentRunUpdateOne) Where(ps ...predicate.ProviderAssignmentRun) *ProviderAssignmentRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderAssignmentRunUpdateOne) Select(field string, fields ...string) *ProviderAssignmentRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderAssignmentRun entity.
func (_u *ProviderAssignmentRunUpdateOne) Save(ctx context.Context) (*ProviderAssignmentRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderAssignmentRunUpdateOne) SaveX(ctx context.Context) *ProviderAssignmentRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderAssignmentRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderAssignmentRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderAssignmentRunUpdateOne) check() error {
	if v, ok := _u.mutation.AssignedProviderID(); ok {
		if err := providerassignmentrun.AssignedProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "assigned_provider_id", err: fmt.Errorf(`ent: validator failed for field "ProviderAssignmentRun.assigned_provider_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Trigger(); ok {
		if err := providerassignmentrun.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "ProviderAssignmentRun.trigger": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := providerassignmentrun.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "ProviderAssignmentRun.result": %w`, err)}
		}
	}
	if _u.mutation.PaymentOrderCleared() && len(_u.mutation.PaymentOrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProviderAssignmentRun.payment_order"`)
	}
	return nil
}

func (_u *ProviderAssignmentRunUpdateOne) sqlSave(ctx context.Context) (_node *ProviderAssignmentRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerassignmentrun.Table, providerassignmentrun.Columns, sqlgraph.NewFieldSpec(providerassignmentrun.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProviderAssignmentRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providerassignmentrun.FieldID)
		for _, f := range fields {
			if !providerassignmentrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != providerassignmentrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AssignedProviderID(); ok {
		_spec.SetField(providerassignmentrun.FieldAssignedProviderID, field.TypeString, value)
	}
	if _u.mutation.AssignedProviderIDCleared() {
		_spec.ClearField(providerassignmentrun.FieldAssignedProviderID, field.TypeString)
	}
	if value, ok := _u.mutation.AttemptedAt(); ok {
		_spec.SetField(providerassignmentrun.FieldAttemptedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(providerassignmentrun.FieldTrigger, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(providerassignmentrun.FieldResult, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsedFallback(); ok {
		_spec.SetField(providerassignmentrun.FieldUsedFallback, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MarketBuyRateSnapshot(); ok {
		_spec.SetField(providerassignmentrun.FieldMarketBuyRateSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketBuyRateSnapshot(); ok {
		_spec.AddField(providerassignmentrun.FieldMarketBuyRateSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.MarketBuyRateSnapshotCleared() {
		_spec.ClearField(providerassignmentrun.FieldMarketBuyRateSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MarketSellRateSnapshot(); ok {
		_spec.SetField(providerassignmentrun.FieldMarketSellRateSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketSellRateSnapshot(); ok {
		_spec.AddField(providerassignmentrun.FieldMarketSellRateSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.MarketSellRateSnapshotCleared() {
		_spec.ClearField(providerassignmentrun.FieldMarketSellRateSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(providerassignmentrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(providerassignmentrun.FieldErrorMessage, field.TypeString)
	}
	if _u.mutation.PaymentOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerassignmentrun.PaymentOrderTable,
			Columns: []string{providerassignmentrun.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerassignmentrun.PaymentOrderTable,
			Columns: []string{providerassignmentrun.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProviderOrderTokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerassignmentrun.ProviderOrderTokenTable,
			Columns: []string{providerassignmentrun.ProviderOrderTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerordertoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderOrderTokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerassignmentrun.ProviderOrderTokenTable,
			Columns: []string{providerassignmentrun.ProviderOrderTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerordertoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProviderAssignmentRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerassignmentrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
