// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/paycrest/aggregator/ent/fiatcurrency"
	"github.com/paycrest/aggregator/ent/predicate"
	"github.com/paycrest/aggregator/ent/providerbalances"
	"github.com/paycrest/aggregator/ent/providerprofile"
	"github.com/paycrest/aggregator/ent/token"
)

// ProviderBalancesQuery is the builder for querying ProviderBalances entities.
type ProviderBalancesQuery struct {
	config
	ctx              *QueryContext
	order            []providerbalances.OrderOption
	inters           []Interceptor
	predicates       []predicate.ProviderBalances
	withProvider     *ProviderProfileQuery
	withFiatCurrency *FiatCurrencyQuery
	withToken        *TokenQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProviderBalancesQuery builder.
func (_q *ProviderBalancesQuery) Where(ps ...predicate.ProviderBalances) *ProviderBalancesQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ProviderBalancesQuery) Limit(limit int) *ProviderBalancesQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ProviderBalancesQuery) Offset(offset int) *ProviderBalancesQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ProviderBalancesQuery) Unique(unique bool) *ProviderBalancesQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ProviderBalancesQuery) Order(o ...providerbalances.OrderOption) *ProviderBalancesQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProvider chains the current query on the "provider" edge.
func (_q *ProviderBalancesQuery) QueryProvider() *ProviderProfileQuery {
	query := (&ProviderProfileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(providerbalances.Table, providerbalances.FieldID, selector),
			sqlgraph.To(providerprofile.Table, providerprofile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, providerbalances.ProviderTable, providerbalances.ProviderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFiatCurrency chains the current query on the "fiat_currency" edge.
func (_q *ProviderBalancesQuery) QueryFiatCurrency() *FiatCurrencyQuery {
	query := (&FiatCurrencyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(providerbalances.Table, providerbalances.FieldID, selector),
			sqlgraph.To(fiatcurrency.Table, fiatcurrency.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, providerbalances.FiatCurrencyTable, providerbalances.FiatCurrencyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryToken chains the current query on the "token" edge.
func (_q *ProviderBalancesQuery) QueryToken() *TokenQuery {
	query := (&TokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(providerbalances.Table, providerbalances.FieldID, selector),
			sqlgraph.To(token.Table, token.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, providerbalances.TokenTable, providerbalances.TokenColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProviderBalances entity from the query.
// Returns a *NotFoundError when no ProviderBalances was found.
func (_q *ProviderBalancesQuery) First(ctx context.Context) (*ProviderBalances, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{providerbalances.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ProviderBalancesQuery) FirstX(ctx context.Context) *ProviderBalances {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProviderBalances ID from the query.
// Returns a *NotFoundError when no ProviderBalances ID was found.
func (_q *ProviderBalancesQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{providerbalances.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ProviderBalancesQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProviderBalances entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProviderBalances entity is found.
// Returns a *NotFoundError when no ProviderBalances entities are found.
func (_q *ProviderBalancesQuery) Only(ctx context.Context) (*ProviderBalances, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{providerbalances.Label}
	default:
		return nil, &NotSingularError{providerbalances.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ProviderBalancesQuery) OnlyX(ctx context.Context) *ProviderBalances {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProviderBalances ID in the query.
// Returns a *NotSingularError when more than one ProviderBalances ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ProviderBalancesQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{providerbalances.Label}
	default:
		err = &NotSingularError{providerbalances.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ProviderBalancesQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProviderBalancesSlice.
func (_q *ProviderBalancesQuery) All(ctx context.Context) ([]*ProviderBalances, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProviderBalances, *ProviderBalancesQuery]()
	return withInterceptors[[]*ProviderBalances](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ProviderBalancesQuery) AllX(ctx context.Context) []*ProviderBalances {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProviderBalances IDs.
func (_q *ProviderBalancesQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(providerbalances.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ProviderBalancesQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ProviderBalancesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ProviderBalancesQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ProviderBalancesQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ProviderBalancesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ProviderBalancesQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProviderBalancesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ProviderBalancesQuery) Clone() *ProviderBalancesQuery {
	if _q == nil {
		return nil
	}
	return &ProviderBalancesQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]providerbalances.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.ProviderBalances{}, _q.predicates...),
		withProvider:     _q.withProvider.Clone(),
		withFiatCurrency: _q.withFiatCurrency.Clone(),
		withToken:        _q.withToken.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProvider tells the query-builder to eager-load the nodes that are connected to
// the "provider" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProviderBalancesQuery) WithProvider(opts ...func(*ProviderProfileQuery)) *ProviderBalancesQuery {
	query := (&ProviderProfileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProvider = query
	return _q
}

// WithFiatCurrency tells the query-builder to eager-load the nodes that are connected to
// the "fiat_currency" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProviderBalancesQuery) WithFiatCurrency(opts ...func(*FiatCurrencyQuery)) *ProviderBalancesQuery {
	query := (&FiatCurrencyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFiatCurrency = query
	return _q
}

// WithToken tells the query-builder to eager-load the nodes that are connected to
// the "token" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProviderBalancesQuery) WithToken(opts ...func(*TokenQuery)) *ProviderBalancesQuery {
	query := (&TokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withToken = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AvailableBalance decimal.Decimal `json:"available_balance,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProviderBalances.Query().
//		GroupBy(providerbalances.FieldAvailableBalance).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ProviderBalancesQuery) GroupBy(field string, fields ...string) *ProviderBalancesGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProviderBalancesGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = providerbalances.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AvailableBalance decimal.Decimal `json:"available_balance,omitempty"`
//	}
//
//	client.ProviderBalances.Query().
//		Select(providerbalances.FieldAvailableBalance).
//		Scan(ctx, &v)
func (_q *ProviderBalancesQuery) Select(fields ...string) *ProviderBalancesSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ProviderBalancesSelect{ProviderBalancesQuery: _q}
	sbuild.label = providerbalances.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProviderBalancesSelect configured with the given aggregations.
func (_q *ProviderBalancesQuery) Aggregate(fns ...AggregateFunc) *ProviderBalancesSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ProviderBalancesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !providerbalances.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ProviderBalancesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProviderBalances, error) {
	var (
		nodes       = []*ProviderBalances{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withProvider != nil,
			_q.withFiatCurrency != nil,
			_q.withToken != nil,
		}
	)
	if _q.withProvider != nil || _q.withFiatCurrency != nil || _q.withToken != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, providerbalances.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProviderBalances).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProviderBalances{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProvider; query != nil {
		if err := _q.loadProvider(ctx, query, nodes, nil,
			func(n *ProviderBalances, e *ProviderProfile) { n.Edges.Provider = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFiatCurrency; query != nil {
		if err := _q.loadFiatCurrency(ctx, query, nodes, nil,
			func(n *ProviderBalances, e *FiatCurrency) { n.Edges.FiatCurrency = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withToken; query != nil {
		if err := _q.loadToken(ctx, query, nodes, nil,
			func(n *ProviderBalances, e *Token) { n.Edges.Token = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ProviderBalancesQuery) loadProvider(ctx context.Context, query *ProviderProfileQuery, nodes []*ProviderBalances, init func(*ProviderBalances), assign func(*ProviderBalances, *ProviderProfile)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*ProviderBalances)
	for i := range nodes {
		if nodes[i].provider_profile_provider_balances == nil {
			continue
		}
		fk := *nodes[i].provider_profile_provider_balances
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(providerprofile.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "provider_profile_provider_balances" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProviderBalancesQuery) loadFiatCurrency(ctx context.Context, query *FiatCurrencyQuery, nodes []*ProviderBalances, init func(*ProviderBalances), assign func(*ProviderBalances, *FiatCurrency)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProviderBalances)
	for i := range nodes {
		if nodes[i].fiat_currency_provider_balances == nil {
			continue
		}
		fk := *nodes[i].fiat_currency_provider_balances
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(fiatcurrency.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "fiat_currency_provider_balances" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProviderBalancesQuery) loadToken(ctx context.Context, query *TokenQuery, nodes []*ProviderBalances, init func(*ProviderBalances), assign func(*ProviderBalances, *Token)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ProviderBalances)
	for i := range nodes {
		if nodes[i].token_provider_balances == nil {
			continue
		}
		fk := *nodes[i].token_provider_balances
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(token.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "token_provider_balances" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ProviderBalancesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ProviderBalancesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(providerbalances.Table, providerbalances.Columns, sqlgraph.NewFieldSpec(providerbalances.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providerbalances.FieldID)
		for i := range fields {
			if fields[i] != providerbalances.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ProviderBalancesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(providerbalances.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = providerbalances.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProviderBalancesGroupBy is the group-by builder for ProviderBalances entities.
type ProviderBalancesGroupBy struct {
	selector
	build *ProviderBalancesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ProviderBalancesGroupBy) Aggregate(fns ...AggregateFunc) *ProviderBalancesGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ProviderBalancesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProviderBalancesQuery, *ProviderBalancesGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ProviderBalancesGroupBy) sqlScan(ctx context.Context, root *ProviderBalancesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProviderBalancesSelect is the builder for selecting fields of ProviderBalances entities.
type ProviderBalancesSelect struct {
	*ProviderBalancesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ProviderBalancesSelect) Aggregate(fns ...AggregateFunc) *ProviderBalancesSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ProviderBalancesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProviderBalancesQuery, *ProviderBalancesSelect](ctx, _s.ProviderBalancesQuery, _s, _s.inters, v)
}

func (_s *ProviderBalancesSelect) sqlScan(ctx context.Context, root *ProviderBalancesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
