// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/paycrest/aggregator/ent/predicate"
	"github.com/paycrest/aggregator/ent/providerorderassignment"
)

// ProviderOrderAssignmentDelete is the builder for deleting a ProviderOrderAssignment entity.
type ProviderOrderAssignmentDelete struct {
	config
	hooks    []Hook
	mutation *ProviderOrderAssignmentMutation
}

// Where appends a list predicates to the ProviderOrderAssignmentDelete builder.
func (_d *ProviderOrderAssignmentDelete) Where(ps ...predicate.ProviderOrderAssignment) *ProviderOrderAssignmentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProviderOrderAssignmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProviderOrderAssignmentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProviderOrderAssignmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(providerorderassignment.Table, sqlgraph.NewFieldSpec(providerorderassignment.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProviderOrderAssignmentDeleteOne is the builder for deleting a single ProviderOrderAssignment entity.
type ProviderOrderAssignmentDeleteOne struct {
	_d *ProviderOrderAssignmentDelete
}

// Where appends a list predicates to the ProviderOrderAssignmentDelete builder.
func (_d *ProviderOrderAssignmentDeleteOne) Where(ps ...predicate.ProviderOrderAssignment) *ProviderOrderAssignmentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProviderOrderAssignmentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{providerorderassignment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProviderOrderAssignmentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
