// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/paycrest/aggregator/ent/predicate"
	"github.com/paycrest/aggregator/ent/providercurrencies"
)

// ProviderCurrenciesDelete is the builder for deleting a ProviderCurrencies entity.
type ProviderCurrenciesDelete struct {
	config
	hooks    []Hook
	mutation *ProviderCurrenciesMutation
}

// Where appends a list predicates to the ProviderCurrenciesDelete builder.
func (pcd *ProviderCurrenciesDelete) Where(ps ...predicate.ProviderCurrencies) *ProviderCurrenciesDelete {
	pcd.mutation.Where(ps...)
	return pcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pcd *ProviderCurrenciesDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pcd.sqlExec, pcd.mutation, pcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pcd *ProviderCurrenciesDelete) ExecX(ctx context.Context) int {
	n, err := pcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pcd *ProviderCurrenciesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(providercurrencies.Table, sqlgraph.NewFieldSpec(providercurrencies.FieldID, field.TypeUUID))
	if ps := pcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pcd.mutation.done = true
	return affected, err
}

// ProviderCurrenciesDeleteOne is the builder for deleting a single ProviderCurrencies entity.
type ProviderCurrenciesDeleteOne struct {
	pcd *ProviderCurrenciesDelete
}

// Where appends a list predicates to the ProviderCurrenciesDelete builder.
func (pcdo *ProviderCurrenciesDeleteOne) Where(ps ...predicate.ProviderCurrencies) *ProviderCurrenciesDeleteOne {
	pcdo.pcd.mutation.Where(ps...)
	return pcdo
}

// Exec executes the deletion query.
func (pcdo *ProviderCurrenciesDeleteOne) Exec(ctx context.Context) error {
	n, err := pcdo.pcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{providercurrencies.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pcdo *ProviderCurrenciesDeleteOne) ExecX(ctx context.Context) {
	if err := pcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
