// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/paycrest/aggregator/ent/providerfiataccount"
	"github.com/paycrest/aggregator/ent/providerprofile"
)

// ProviderFiatAccountCreate is the builder for creating a ProviderFiatAccount entity.
type ProviderFiatAccountCreate struct {
	config
	mutation *ProviderFiatAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (pfac *ProviderFiatAccountCreate) SetCreatedAt(t time.Time) *ProviderFiatAccountCreate {
	pfac.mutation.SetCreatedAt(t)
	return pfac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pfac *ProviderFiatAccountCreate) SetNillableCreatedAt(t *time.Time) *ProviderFiatAccountCreate {
	if t != nil {
		pfac.SetCreatedAt(*t)
	}
	return pfac
}

// SetUpdatedAt sets the "updated_at" field.
func (pfac *ProviderFiatAccountCreate) SetUpdatedAt(t time.Time) *ProviderFiatAccountCreate {
	pfac.mutation.SetUpdatedAt(t)
	return pfac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pfac *ProviderFiatAccountCreate) SetNillableUpdatedAt(t *time.Time) *ProviderFiatAccountCreate {
	if t != nil {
		pfac.SetUpdatedAt(*t)
	}
	return pfac
}

// SetInstitution sets the "institution" field.
func (pfac *ProviderFiatAccountCreate) SetInstitution(s string) *ProviderFiatAccountCreate {
	pfac.mutation.SetInstitution(s)
	return pfac
}

// SetAccountIdentifier sets the "account_identifier" field.
func (pfac *ProviderFiatAccountCreate) SetAccountIdentifier(s string) *ProviderFiatAccountCreate {
	pfac.mutation.SetAccountIdentifier(s)
	return pfac
}

// SetAccountName sets the "account_name" field.
func (pfac *ProviderFiatAccountCreate) SetAccountName(s string) *ProviderFiatAccountCreate {
	pfac.mutation.SetAccountName(s)
	return pfac
}

// SetID sets the "id" field.
func (pfac *ProviderFiatAccountCreate) SetID(u uuid.UUID) *ProviderFiatAccountCreate {
	pfac.mutation.SetID(u)
	return pfac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pfac *ProviderFiatAccountCreate) SetNillableID(u *uuid.UUID) *ProviderFiatAccountCreate {
	if u != nil {
		pfac.SetID(*u)
	}
	return pfac
}

// SetProviderID sets the "provider" edge to the ProviderProfile entity by ID.
func (pfac *ProviderFiatAccountCreate) SetProviderID(id string) *ProviderFiatAccountCreate {
	pfac.mutation.SetProviderID(id)
	return pfac
}

// SetProvider sets the "provider" edge to the ProviderProfile entity.
func (pfac *ProviderFiatAccountCreate) SetProvider(p *ProviderProfile) *ProviderFiatAccountCreate {
	return pfac.SetProviderID(p.ID)
}

// Mutation returns the ProviderFiatAccountMutation object of the builder.
func (pfac *ProviderFiatAccountCreate) Mutation() *ProviderFiatAccountMutation {
	return pfac.mutation
}

// Save creates the ProviderFiatAccount in the database.
func (pfac *ProviderFiatAccountCreate) Save(ctx context.Context) (*ProviderFiatAccount, error) {
	pfac.defaults()
	return withHooks(ctx, pfac.sqlSave, pfac.mutation, pfac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pfac *ProviderFiatAccountCreate) SaveX(ctx context.Context) *ProviderFiatAccount {
	v, err := pfac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pfac *ProviderFiatAccountCreate) Exec(ctx context.Context) error {
	_, err := pfac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pfac *ProviderFiatAccountCreate) ExecX(ctx context.Context) {
	if err := pfac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pfac *ProviderFiatAccountCreate) defaults() {
	if _, ok := pfac.mutation.CreatedAt(); !ok {
		v := providerfiataccount.DefaultCreatedAt()
		pfac.mutation.SetCreatedAt(v)
	}
	if _, ok := pfac.mutation.UpdatedAt(); !ok {
		v := providerfiataccount.DefaultUpdatedAt()
		pfac.mutation.SetUpdatedAt(v)
	}
	if _, ok := pfac.mutation.ID(); !ok {
		v := providerfiataccount.DefaultID()
		pfac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pfac *ProviderFiatAccountCreate) check() error {
	if _, ok := pfac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProviderFiatAccount.created_at"`)}
	}
	if _, ok := pfac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProviderFiatAccount.updated_at"`)}
	}
	if _, ok := pfac.mutation.Institution(); !ok {
		return &ValidationError{Name: "institution", err: errors.New(`ent: missing required field "ProviderFiatAccount.institution"`)}
	}
	if v, ok := pfac.mutation.Institution(); ok {
		if err := providerfiataccount.InstitutionValidator(v); err != nil {
			return &ValidationError{Name: "institution", err: fmt.Errorf(`ent: validator failed for field "ProviderFiatAccount.institution": %w`, err)}
		}
	}
	if _, ok := pfac.mutation.AccountIdentifier(); !ok {
		return &ValidationError{Name: "account_identifier", err: errors.New(`ent: missing required field "ProviderFiatAccount.account_identifier"`)}
	}
	if v, ok := pfac.mutation.AccountIdentifier(); ok {
		if err := providerfiataccount.AccountIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "account_identifier", err: fmt.Errorf(`ent: validator failed for field "ProviderFiatAccount.account_identifier": %w`, err)}
		}
	}
	if _, ok := pfac.mutation.AccountName(); !ok {
		return &ValidationError{Name: "account_name", err: errors.New(`ent: missing required field "ProviderFiatAccount.account_name"`)}
	}
	if v, ok := pfac.mutation.AccountName(); ok {
		if err := providerfiataccount.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "ProviderFiatAccount.account_name": %w`, err)}
		}
	}
	if len(pfac.mutation.ProviderIDs()) == 0 {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required edge "ProviderFiatAccount.provider"`)}
	}
	return nil
}

func (pfac *ProviderFiatAccountCreate) sqlSave(ctx context.Context) (*ProviderFiatAccount, error) {
	if err := pfac.check(); err != nil {
		return nil, err
	}
	_node, _spec := pfac.createSpec()
	if err := sqlgraph.CreateNode(ctx, pfac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pfac.mutation.id = &_node.ID
	pfac.mutation.done = true
	return _node, nil
}

func (pfac *ProviderFiatAccountCreate) createSpec() (*ProviderFiatAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderFiatAccount{config: pfac.config}
		_spec = sqlgraph.NewCreateSpec(providerfiataccount.Table, sqlgraph.NewFieldSpec(providerfiataccount.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = pfac.conflict
	if id, ok := pfac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pfac.mutation.CreatedAt(); ok {
		_spec.SetField(providerfiataccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pfac.mutation.UpdatedAt(); ok {
		_spec.SetField(providerfiataccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := pfac.mutation.Institution(); ok {
		_spec.SetField(providerfiataccount.FieldInstitution, field.TypeString, value)
		_node.Institution = value
	}
	if value, ok := pfac.mutation.AccountIdentifier(); ok {
		_spec.SetField(providerfiataccount.FieldAccountIdentifier, field.TypeString, value)
		_node.AccountIdentifier = value
	}
	if value, ok := pfac.mutation.AccountName(); ok {
		_spec.SetField(providerfiataccount.FieldAccountName, field.TypeString, value)
		_node.AccountName = value
	}
	if nodes := pfac.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerfiataccount.ProviderTable,
			Columns: []string{providerfiataccount.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerprofile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.provider_profile_fiat_accounts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderFiatAccount.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderFiatAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (pfac *ProviderFiatAccountCreate) OnConflict(opts ...sql.ConflictOption) *ProviderFiatAccountUpsertOne {
	pfac.conflict = opts
	return &ProviderFiatAccountUpsertOne{
		create: pfac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderFiatAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pfac *ProviderFiatAccountCreate) OnConflictColumns(columns ...string) *ProviderFiatAccountUpsertOne {
	pfac.conflict = append(pfac.conflict, sql.ConflictColumns(columns...))
	return &ProviderFiatAccountUpsertOne{
		create: pfac,
	}
}

type (
	// ProviderFiatAccountUpsertOne is the builder for "upsert"-ing
	//  one ProviderFiatAccount node.
	ProviderFiatAccountUpsertOne struct {
		create *ProviderFiatAccountCreate
	}

	// ProviderFiatAccountUpsert is the "OnConflict" setter.
	ProviderFiatAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderFiatAccountUpsert) SetUpdatedAt(v time.Time) *ProviderFiatAccountUpsert {
	u.Set(providerfiataccount.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderFiatAccountUpsert) UpdateUpdatedAt() *ProviderFiatAccountUpsert {
	u.SetExcluded(providerfiataccount.FieldUpdatedAt)
	return u
}

// SetInstitution sets the "institution" field.
func (u *ProviderFiatAccountUpsert) SetInstitution(v string) *ProviderFiatAccountUpsert {
	u.Set(providerfiataccount.FieldInstitution, v)
	return u
}

// UpdateInstitution sets the "institution" field to the value that was provided on create.
func (u *ProviderFiatAccountUpsert) UpdateInstitution() *ProviderFiatAccountUpsert {
	u.SetExcluded(providerfiataccount.FieldInstitution)
	return u
}

// SetAccountIdentifier sets the "account_identifier" field.
func (u *ProviderFiatAccountUpsert) SetAccountIdentifier(v string) *ProviderFiatAccountUpsert {
	u.Set(providerfiataccount.FieldAccountIdentifier, v)
	return u
}

// UpdateAccountIdentifier sets the "account_identifier" field to the value that was provided on create.
func (u *ProviderFiatAccountUpsert) UpdateAccountIdentifier() *ProviderFiatAccountUpsert {
	u.SetExcluded(providerfiataccount.FieldAccountIdentifier)
	return u
}

// SetAccountName sets the "account_name" field.
func (u *ProviderFiatAccountUpsert) SetAccountName(v string) *ProviderFiatAccountUpsert {
	u.Set(providerfiataccount.FieldAccountName, v)
	return u
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *ProviderFiatAccountUpsert) UpdateAccountName() *ProviderFiatAccountUpsert {
	u.SetExcluded(providerfiataccount.FieldAccountName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ProviderFiatAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(providerfiataccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProviderFiatAccountUpsertOne) UpdateNewValues() *ProviderFiatAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(providerfiataccount.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(providerfiataccount.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderFiatAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProviderFiatAccountUpsertOne) Ignore() *ProviderFiatAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderFiatAccountUpsertOne) DoNothing() *ProviderFiatAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderFiatAccountCreate.OnConflict
// documentation for more info.
func (u *ProviderFiatAccountUpsertOne) Update(set func(*ProviderFiatAccountUpsert)) *ProviderFiatAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderFiatAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderFiatAccountUpsertOne) SetUpdatedAt(v time.Time) *ProviderFiatAccountUpsertOne {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderFiatAccountUpsertOne) UpdateUpdatedAt() *ProviderFiatAccountUpsertOne {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetInstitution sets the "institution" field.
func (u *ProviderFiatAccountUpsertOne) SetInstitution(v string) *ProviderFiatAccountUpsertOne {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.SetInstitution(v)
	})
}

// UpdateInstitution sets the "institution" field to the value that was provided on create.
func (u *ProviderFiatAccountUpsertOne) UpdateInstitution() *ProviderFiatAccountUpsertOne {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.UpdateInstitution()
	})
}

// SetAccountIdentifier sets the "account_identifier" field.
func (u *ProviderFiatAccountUpsertOne) SetAccountIdentifier(v string) *ProviderFiatAccountUpsertOne {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.SetAccountIdentifier(v)
	})
}

// UpdateAccountIdentifier sets the "account_identifier" field to the value that was provided on create.
func (u *ProviderFiatAccountUpsertOne) UpdateAccountIdentifier() *ProviderFiatAccountUpsertOne {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.UpdateAccountIdentifier()
	})
}

// SetAccountName sets the "account_name" field.
func (u *ProviderFiatAccountUpsertOne) SetAccountName(v string) *ProviderFiatAccountUpsertOne {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.SetAccountName(v)
	})
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *ProviderFiatAccountUpsertOne) UpdateAccountName() *ProviderFiatAccountUpsertOne {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.UpdateAccountName()
	})
}

// Exec executes the query.
func (u *ProviderFiatAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderFiatAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderFiatAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProviderFiatAccountUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ProviderFiatAccountUpsertOne.ID is not supported by MySQL driver. Use ProviderFiatAccountUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProviderFiatAccountUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProviderFiatAccountCreateBulk is the builder for creating many ProviderFiatAccount entities in bulk.
type ProviderFiatAccountCreateBulk struct {
	config
	err      error
	builders []*ProviderFiatAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the ProviderFiatAccount entities in the database.
func (pfacb *ProviderFiatAccountCreateBulk) Save(ctx context.Context) ([]*ProviderFiatAccount, error) {
	if pfacb.err != nil {
		return nil, pfacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pfacb.builders))
	nodes := make([]*ProviderFiatAccount, len(pfacb.builders))
	mutators := make([]Mutator, len(pfacb.builders))
	for i := range pfacb.builders {
		func(i int, root context.Context) {
			builder := pfacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderFiatAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pfacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = pfacb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pfacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pfacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pfacb *ProviderFiatAccountCreateBulk) SaveX(ctx context.Context) []*ProviderFiatAccount {
	v, err := pfacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pfacb *ProviderFiatAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := pfacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pfacb *ProviderFiatAccountCreateBulk) ExecX(ctx context.Context) {
	if err := pfacb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderFiatAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderFiatAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (pfacb *ProviderFiatAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProviderFiatAccountUpsertBulk {
	pfacb.conflict = opts
	return &ProviderFiatAccountUpsertBulk{
		create: pfacb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderFiatAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pfacb *ProviderFiatAccountCreateBulk) OnConflictColumns(columns ...string) *ProviderFiatAccountUpsertBulk {
	pfacb.conflict = append(pfacb.conflict, sql.ConflictColumns(columns...))
	return &ProviderFiatAccountUpsertBulk{
		create: pfacb,
	}
}

// ProviderFiatAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of ProviderFiatAccount nodes.
type ProviderFiatAccountUpsertBulk struct {
	create *ProviderFiatAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProviderFiatAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(providerfiataccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProviderFiatAccountUpsertBulk) UpdateNewValues() *ProviderFiatAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(providerfiataccount.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(providerfiataccount.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderFiatAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProviderFiatAccountUpsertBulk) Ignore() *ProviderFiatAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderFiatAccountUpsertBulk) DoNothing() *ProviderFiatAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderFiatAccountCreateBulk.OnConflict
// documentation for more info.
func (u *ProviderFiatAccountUpsertBulk) Update(set func(*ProviderFiatAccountUpsert)) *ProviderFiatAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderFiatAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderFiatAccountUpsertBulk) SetUpdatedAt(v time.Time) *ProviderFiatAccountUpsertBulk {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderFiatAccountUpsertBulk) UpdateUpdatedAt() *ProviderFiatAccountUpsertBulk {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetInstitution sets the "institution" field.
func (u *ProviderFiatAccountUpsertBulk) SetInstitution(v string) *ProviderFiatAccountUpsertBulk {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.SetInstitution(v)
	})
}

// UpdateInstitution sets the "institution" field to the value that was provided on create.
func (u *ProviderFiatAccountUpsertBulk) UpdateInstitution() *ProviderFiatAccountUpsertBulk {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.UpdateInstitution()
	})
}

// SetAccountIdentifier sets the "account_identifier" field.
func (u *ProviderFiatAccountUpsertBulk) SetAccountIdentifier(v string) *ProviderFiatAccountUpsertBulk {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.SetAccountIdentifier(v)
	})
}

// UpdateAccountIdentifier sets the "account_identifier" field to the value that was provided on create.
func (u *ProviderFiatAccountUpsertBulk) UpdateAccountIdentifier() *ProviderFiatAccountUpsertBulk {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.UpdateAccountIdentifier()
	})
}

// SetAccountName sets the "account_name" field.
func (u *ProviderFiatAccountUpsertBulk) SetAccountName(v string) *ProviderFiatAccountUpsertBulk {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.SetAccountName(v)
	})
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *ProviderFiatAccountUpsertBulk) UpdateAccountName() *ProviderFiatAccountUpsertBulk {
	return u.Update(func(s *ProviderFiatAccountUpsert) {
		s.UpdateAccountName()
	})
}

// Exec executes the query.
func (u *ProviderFiatAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProviderFiatAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderFiatAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderFiatAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
