// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/paycrest/aggregator/ent/paymentorder"
	"github.com/paycrest/aggregator/ent/predicate"
	"github.com/paycrest/aggregator/ent/receiveaddress"
)

// ReceiveAddressQuery is the builder for querying ReceiveAddress entities.
type ReceiveAddressQuery struct {
	config
	ctx              *QueryContext
	order            []receiveaddress.OrderOption
	inters           []Interceptor
	predicates       []predicate.ReceiveAddress
	withPaymentOrder *PaymentOrderQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReceiveAddressQuery builder.
func (_q *ReceiveAddressQuery) Where(ps ...predicate.ReceiveAddress) *ReceiveAddressQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ReceiveAddressQuery) Limit(limit int) *ReceiveAddressQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ReceiveAddressQuery) Offset(offset int) *ReceiveAddressQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ReceiveAddressQuery) Unique(unique bool) *ReceiveAddressQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ReceiveAddressQuery) Order(o ...receiveaddress.OrderOption) *ReceiveAddressQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPaymentOrder chains the current query on the "payment_order" edge.
func (_q *ReceiveAddressQuery) QueryPaymentOrder() *PaymentOrderQuery {
	query := (&PaymentOrderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(receiveaddress.Table, receiveaddress.FieldID, selector),
			sqlgraph.To(paymentorder.Table, paymentorder.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, receiveaddress.PaymentOrderTable, receiveaddress.PaymentOrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ReceiveAddress entity from the query.
// Returns a *NotFoundError when no ReceiveAddress was found.
func (_q *ReceiveAddressQuery) First(ctx context.Context) (*ReceiveAddress, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{receiveaddress.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ReceiveAddressQuery) FirstX(ctx context.Context) *ReceiveAddress {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReceiveAddress ID from the query.
// Returns a *NotFoundError when no ReceiveAddress ID was found.
func (_q *ReceiveAddressQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{receiveaddress.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ReceiveAddressQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReceiveAddress entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReceiveAddress entity is found.
// Returns a *NotFoundError when no ReceiveAddress entities are found.
func (_q *ReceiveAddressQuery) Only(ctx context.Context) (*ReceiveAddress, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{receiveaddress.Label}
	default:
		return nil, &NotSingularError{receiveaddress.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ReceiveAddressQuery) OnlyX(ctx context.Context) *ReceiveAddress {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReceiveAddress ID in the query.
// Returns a *NotSingularError when more than one ReceiveAddress ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ReceiveAddressQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{receiveaddress.Label}
	default:
		err = &NotSingularError{receiveaddress.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ReceiveAddressQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReceiveAddresses.
func (_q *ReceiveAddressQuery) All(ctx context.Context) ([]*ReceiveAddress, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ReceiveAddress, *ReceiveAddressQuery]()
	return withInterceptors[[]*ReceiveAddress](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ReceiveAddressQuery) AllX(ctx context.Context) []*ReceiveAddress {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReceiveAddress IDs.
func (_q *ReceiveAddressQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(receiveaddress.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ReceiveAddressQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ReceiveAddressQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ReceiveAddressQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ReceiveAddressQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ReceiveAddressQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ReceiveAddressQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReceiveAddressQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ReceiveAddressQuery) Clone() *ReceiveAddressQuery {
	if _q == nil {
		return nil
	}
	return &ReceiveAddressQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]receiveaddress.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.ReceiveAddress{}, _q.predicates...),
		withPaymentOrder: _q.withPaymentOrder.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPaymentOrder tells the query-builder to eager-load the nodes that are connected to
// the "payment_order" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ReceiveAddressQuery) WithPaymentOrder(opts ...func(*PaymentOrderQuery)) *ReceiveAddressQuery {
	query := (&PaymentOrderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPaymentOrder = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReceiveAddress.Query().
//		GroupBy(receiveaddress.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ReceiveAddressQuery) GroupBy(field string, fields ...string) *ReceiveAddressGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReceiveAddressGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = receiveaddress.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ReceiveAddress.Query().
//		Select(receiveaddress.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ReceiveAddressQuery) Select(fields ...string) *ReceiveAddressSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ReceiveAddressSelect{ReceiveAddressQuery: _q}
	sbuild.label = receiveaddress.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReceiveAddressSelect configured with the given aggregations.
func (_q *ReceiveAddressQuery) Aggregate(fns ...AggregateFunc) *ReceiveAddressSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ReceiveAddressQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !receiveaddress.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ReceiveAddressQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReceiveAddress, error) {
	var (
		nodes       = []*ReceiveAddress{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withPaymentOrder != nil,
		}
	)
	if _q.withPaymentOrder != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, receiveaddress.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ReceiveAddress).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ReceiveAddress{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPaymentOrder; query != nil {
		if err := _q.loadPaymentOrder(ctx, query, nodes, nil,
			func(n *ReceiveAddress, e *PaymentOrder) { n.Edges.PaymentOrder = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ReceiveAddressQuery) loadPaymentOrder(ctx context.Context, query *PaymentOrderQuery, nodes []*ReceiveAddress, init func(*ReceiveAddress), assign func(*ReceiveAddress, *PaymentOrder)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ReceiveAddress)
	for i := range nodes {
		if nodes[i].payment_order_receive_address == nil {
			continue
		}
		fk := *nodes[i].payment_order_receive_address
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(paymentorder.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "payment_order_receive_address" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ReceiveAddressQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ReceiveAddressQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(receiveaddress.Table, receiveaddress.Columns, sqlgraph.NewFieldSpec(receiveaddress.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, receiveaddress.FieldID)
		for i := range fields {
			if fields[i] != receiveaddress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ReceiveAddressQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(receiveaddress.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = receiveaddress.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReceiveAddressGroupBy is the group-by builder for ReceiveAddress entities.
type ReceiveAddressGroupBy struct {
	selector
	build *ReceiveAddressQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ReceiveAddressGroupBy) Aggregate(fns ...AggregateFunc) *ReceiveAddressGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ReceiveAddressGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReceiveAddressQuery, *ReceiveAddressGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ReceiveAddressGroupBy) sqlScan(ctx context.Context, root *ReceiveAddressQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReceiveAddressSelect is the builder for selecting fields of ReceiveAddress entities.
type ReceiveAddressSelect struct {
	*ReceiveAddressQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ReceiveAddressSelect) Aggregate(fns ...AggregateFunc) *ReceiveAddressSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ReceiveAddressSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReceiveAddressQuery, *ReceiveAddressSelect](ctx, _s.ReceiveAddressQuery, _s, _s.inters, v)
}

func (_s *ReceiveAddressSelect) sqlScan(ctx context.Context, root *ReceiveAddressQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
