// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/paycrest/aggregator/ent/predicate"
	"github.com/paycrest/aggregator/ent/senderfiataccount"
)

// SenderFiatAccountDelete is the builder for deleting a SenderFiatAccount entity.
type SenderFiatAccountDelete struct {
	config
	hooks    []Hook
	mutation *SenderFiatAccountMutation
}

// Where appends a list predicates to the SenderFiatAccountDelete builder.
func (_d *SenderFiatAccountDelete) Where(ps ...predicate.SenderFiatAccount) *SenderFiatAccountDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SenderFiatAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SenderFiatAccountDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SenderFiatAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(senderfiataccount.Table, sqlgraph.NewFieldSpec(senderfiataccount.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SenderFiatAccountDeleteOne is the builder for deleting a single SenderFiatAccount entity.
type SenderFiatAccountDeleteOne struct {
	_d *SenderFiatAccountDelete
}

// Where appends a list predicates to the SenderFiatAccountDelete builder.
func (_d *SenderFiatAccountDeleteOne) Where(ps ...predicate.SenderFiatAccount) *SenderFiatAccountDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SenderFiatAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{senderfiataccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SenderFiatAccountDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
