name: Ent CI
on:
  # Run whenever code is changed in the master branch,
  push:
    branches:
      - main
  # Run on PRs where something changed under the `ent/` or `ent/migrate/migrations/` directory.
  pull_request:
    paths:
      - 'ent/*'
      # - 'ent/migrate/migrations/*'
    branches: [ "main" ]

jobs:
  lint:
    services:
      # Spin up a postgres:10 container to be used as the dev-database for analysis.
      postgres:
        image: postgres:10
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      # - uses: ariga/atlas-action@v0
      #   with:
      #     dir: ent/migrate/migrations
      #     dir-format: golang-migrate # Or: atlas, goose, dbmate
      #     dev-url: postgres://postgres:pass@localhost:5432/test?sslmode=disable
        
      - uses: ent/contrib/ci@master